### ISSUE TITLE
Disable labels

### ISSUE THREAD

**Issue by MarcDahlem** [jjoe64/GraphView#116]
Hi,

is there a possibility to disable the labels, for example on small devices?
It would also be nice to disable vertical and horizontal labels independently.

One workaround for disabeling the vertical labels is graphView.getGraphViewStyle().setVerticalLabelsWidth(1);

But I wasn't able to do the same for the horizontal labels.

\BR
Marc

**Comment by enoky** [comment]
I get an error saying "Cannot Resolve Method". How do I remove all labels in a LineGraphSeries?

**Comment by penn5** [comment]
Is this still possible? I don't seem to be able to use it (No Such Method).

Could you point me in the right direction for the latest version?

Thanks!
