### ISSUE TITLE
Show only X an Y axis

### ISSUE THREAD

**Issue by siempredelao** [jjoe64/GraphView#132]
Hi! I would like to show only X and Y axis, in order to know when a value is positive and negative.
For example, I would like something like this:
    graphView.getGraphViewStyle().setGridColor(Color.TRANSPARENT);
    graphView.getGraphViewStyle().setAxisColor(Color.WHITE);

Thanks!

**Comment by ajithkpistar** [comment]
Even Iwant to show only single x and y axis not all grids how can i do it????Pls its urgent....

**Comment by jjoe64** [comment]
take a look at the setGridStyle(NONE) and setHighlightZeroLines(true) methods of GridLabelRenderer
