### ISSUE TITLE
Appending date/time to real time graph

### ISSUE THREAD

**Issue by baseball07** [jjoe64/GraphView#211]
Hi, is there a way to append the date/time to the real time graph.  Currently, I am plotting the real time Y axis data vs data-in iterations, by implementing a counter as below:

  public void run()
        {
         textView1.setText(s); 
         X += 1;  //increment counter for plotting
         data.appendData(new GraphViewData(X, d1), false, 10); 
         graph.addSeries(data);
         }

Right now I am implementing the current date/time as below, but the same date/time appears at the beginning and end of the graph.  It would be nice to match the times, i.e. showing the most recent data-in value as the current time and the previous data values as the times when they were plotted.  

final DateFormat dateTimeFormatter = DateFormat.getDateTimeInstance(); 

graph.setCustomLabelFormatter(new CustomLabelFormatter(){
        @Override
        public String formatLabel(double value, boolean isValueX) 
        {
            if (isValueX)
            {
            return dateTimeFormatter.format(new Date()); 
            }
            return null; 
            }
    });

**Comment by designer68** [comment]
I am working with some real time data fetching from firebase and displaying in y axis, 
I want to show current minute and seconds in x axis

**Comment by CaptainMalzbier** [comment]
Hello guys,

I have the same problem and didn't know where to post it...

I want to display the real time in seconds like 16:16:52 (HH:mm:ss) followed by the next second for example. 

How do I do this?

My code: 

`
public class HomeFragment extends Fragment {

    private final Handler mHandler = new Handler();
    private Runnable mTimerGraph;
    private LineGraphSeries<DataPoint> mSeriesGraph;
    private boolean scrollToEnd = true;
    public Button bStartStop;
    private Calendar mCalendar;
    private DateFormat mDateFormat = new SimpleDateFormat("HH:mm:ss:SS");


    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, Bundle savedInstanceState) {


        mCalendar = Calendar.getInstance();

        View homeView = inflater.inflate(R.layout.fragment_home, container, false);

        GraphView graph = homeView.findViewById(R.id.graph);
        mSeriesGraph = new LineGraphSeries<>();
        graph.addSeries(mSeriesGraph);

        graph.getViewport().setScrollable(true); // enables horizontal scrolling
        graph.getViewport().setScrollableY(true); // enables vertical scrolling
        graph.getViewport().setScalable(true); // enables horizontal zooming and scrolling
        graph.getViewport().setScalableY(true); // enables vertical zooming and scrolling

        graph.getGridLabelRenderer().setLabelFormatter(new DefaultLabelFormatter() {
            @Override
            public String formatLabel(double value, boolean isValueX) {
                if (isValueX) {
                    mCalendar.setTimeInMillis((long) value);
                    System.out.println(mDateFormat.format(mCalendar.getTimeInMillis()));
                    return mDateFormat.format(mCalendar.getTimeInMillis());
                } else {
                    return super.formatLabel(value, isValueX);
                }
            }
        });

        graph.getGridLabelRenderer().setNumHorizontalLabels(3); // only 4 because of the space
        mSeriesGraph.setColor(getResources().getColor(R.color.colorPrimary));

        bStartStop = homeView.findViewById(R.id.bStartStop);
        bStartStop.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {
                if (isScrollToEnd() == false) {
                    setScrollToEnd(true);
                } else {
                    setScrollToEnd(false);
                }
            }
        });

        return homeView;
    }


    @Override
    public void onResume() {
        super.onResume();

        mTimerGraph = new Runnable() {
            @Override
            public void run() {
                //he proceeds 0.01 on x axis in 1000/25 (1 Picture) --> every Second .25

                Calendar cal = Calendar.getInstance();
                Date date = cal.getTime();


                long millis = System.currentTimeMillis();
                double x = (new Long(millis)).doubleValue();
                mCalendar.setTimeInMillis((long) x);

                mSeriesGraph.appendData(new DataPoint(date, getRandom()), true, 100);
                mHandler.postDelayed(this, 1000);
            }
        };
        mHandler.postDelayed(mTimerGraph, 1000);

    }

    @Override
    public void onPause() {
        mHandler.removeCallbacks(mTimerGraph);
        super.onPause();
    }

    double start = -5;
    double end = 5;
    Random mRand = new Random();

    private double getRandom() {
        return start + (mRand.nextDouble() * (end - start));
    }

    public boolean isScrollToEnd() {
        return scrollToEnd;
    }

    public void setScrollToEnd(boolean scrollToEnd) {
        this.scrollToEnd = scrollToEnd;
    }

}`

![graph](https://user-images.githubusercontent.com/19706166/40430576-ba5bdb16-5ea5-11e8-9f39-ebd8f6fbda3c.png)

**Comment by lisandro34** [comment]
Hola saludos, le comento a ver si me pudiesen ayudar soy nuevo en esto, estoy tratando de graficar,  este es el codigo, en el eje x coloco la fecha al parecer todo bien pero cuando me grafica me sale solo en el eje y, no me extiende la linea de la grafica sobre el eje x


public class MainActivity extends AppCompatActivity {

    GraphView graphView;
    LineGraphSeries<DataPoint>series;
    SimpleDateFormat sdf = new SimpleDateFormat(" M/Y");


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);


        graphView = (GraphView)findViewById(R.id.graphView);

        series = new LineGraphSeries<>(getDataPoint());
        graphView.getViewport().setScalable(true);
        graphView.getViewport().setScalableY(true);


        graphView.addSeries(series);

        graphView.getGridLabelRenderer().setLabelFormatter(new DefaultLabelFormatter()
        {

            @Override
            public String formatLabel(double value, boolean isValueX) {

                if (isValueX) {

                    return sdf.format(new Date((long) value));
                } else {
                    return super.formatLabel(value, isValueX);
                }

            }
        });

    }

    private DataPoint[] getDataPoint() {
        DataPoint[] dp = new DataPoint[]{
                new DataPoint(new Date().getTime(),1),
                new DataPoint(new Date().getTime(),22),
        new DataPoint(new Date().getTime(),3),
        new DataPoint(new Date().getTime(),14),
        new DataPoint(new Date().getTime(),9),
        new DataPoint(new Date().getTime(),16),
        new DataPoint(new Date().getTime(),8),
        new DataPoint(new Date().getTime(),2),
                new DataPoint(new Date().getTime(),11),
                new DataPoint(new Date().getTime(),8),
                new DataPoint(new Date().getTime(),17),
        };
        return dp;
    }


}
