### ISSUE TITLE
Not Rounded Corners in a Series !

### ISSUE THREAD

**Issue by Lir10** [jjoe64/GraphView#242]
I did managed to draw the graph that i wanted but some how I'm getting rounded corners at the end of the graph. 

How can i change the corner from rounded to a straight corner like this:
![screenshot_2014-11-07-15-22-57 1](https://cloud.githubusercontent.com/assets/7545176/4953542/227d9380-6682-11e4-88fd-4ad1f4a5ac14.png)

**Comment by Ubmeje** [comment]
Maybe you could try
PointsGraphSeries.CustomShape()
 
Put one dot whit same color as background  on the end of your line
paint.setStrokeWidth(16);
canvas.drawLine(x +8, y - 16, x + 8, y + 16, paint);

But parts of the grid will also be cover.

**Comment by jjoe64** [comment]
too old ticket and graphview version
