### ISSUE TITLE
getDrawingCache returns null from GraphView used in a widget

### ISSUE THREAD

**Issue by Daniele-Comi** [jjoe64/GraphView#270]
The method,extend from View by GraphView,getDrawingCache returns null from GraphView used in a widget.
Here the code:
 <code>

            graphView=new LineGraphView(context,"");
            graphView.setManualYAxisBounds(max_freq/1000,0);
            graphViewSeries=new GraphViewSeries(new GraphView.GraphViewData[]{new                   
            GraphView.GraphViewData(0,0)});
            ((LineGraphView)graphView).setDrawBackground(true);
            graphView.addSeries(graphViewSeries);
            graphView.setViewPort(1, 1);
            graphView.setScalable(true);
            graphView.setShowHorizontalLabels(false);
            graphView.setShowVerticalLabels(false);
            graphView.setDrawingCacheEnabled(true);
            graphViewSeries.appendData(new GraphView.GraphViewData(0.4, 900), true, 10);
            graphView.buildDrawingCache(true);
            Bitmap bitmap=graphView.getDrawingCache();
            if(bitmap==null)
                Log.i("BITMAP","NULL");
            remoteViews.setImageViewBitmap(R.id.widget_cpu_graph,bitmap);
            appWidgetManager.updateAppWidget(widget, remoteViews);
</code>
Any suggestions? Thanks for your help.

**Comment by jjoe64** [comment]
hm sorry i have no idea for that

**Comment by FitzgeraldKrudde** [comment]
This still seems an issue :-( Anybody got a clue why this happens?
This prevents the usage of the GraphView library in widgets (which is a pity).

**Comment by RaghuMadivala** [comment]
GraphView,getDrawingCache returns null from GraphView fix this

**Comment by RaghuMadivala** [comment]
found any solution?

**Comment by FitzgeraldKrudde** [comment]
Nope .. I switched to another charting library (achartengine)..
