### ISSUE TITLE
Real-time series chart goes blank if y value is held constant with 4.0.0

### ISSUE THREAD

**Issue by ptrasatti** [jjoe64/GraphView#271]
Jonas,

   Great job on your Graphview package! I have been using it for about a month and I am developing a real-time monitoring app for some remote sensors I have. I discovered a minor issue in the software which I thought you might want to know about.

Here are the details:

   I just ported my real-time multi-series charting app from GraphView 3.1.3 to 4.0.0.   I am appending data to a single line series and I have noticed that the chart goes blank if the y value is held constant and fills the viewport area. Once y changes, the graph reappears until the line is flat again. I have a 60 value window set on x (no window set for y), scroll to end option set, so the old data scrolls off the left-hand side after 60 updates. Also, if I stop appending and scroll back the graph doesn't paint when the y values are constant. 

Note: the legend still appears on the chart and it doesn't happen if there more than one series on the chart even if they are flat lines with no changes in y values.

I have my app working fairly well with version 3.1.3 and I am trying to use the new features in 4.0.0 which are very cool.

I am also having some scrolling and zooming issues with 4.0.0 but need to investigate those a bit more since I just switched the viewport code to use the new API recently.

Thanks, 

Phil

**Comment by ptrasatti** [comment]
Resolved my scrolling and scaling refresh problems by creating an XML resource file and inflating it in Java code. Still see the refresh issue reported above. 

Phil

**Comment by ptrasatti** [comment]
I fixed this issue and possibly (also issue #280) by adding the following line of code to the Viewport class. The problem is that top and bottom are equal and the grid isn't visible in this case. 

Thanks,

Phil

    public void calcCompleteRange() {
    ....
       if (mCurrentViewport.top == mCurrentViewport.bottom) mCurrentViewport.top++; // pjt - fixes blank screen when range is zero
    }

**Comment by jjoe64** [comment]
thanks it works
