### ISSUE TITLE
Series does not fill the entire chart in v4.0.0

### ISSUE THREAD

**Issue by DonKamillo88** [jjoe64/GraphView#274]
Hi,
When i have 5 data points it's ok, but when I add more points it's look like in image below.
Can you tell me how to fill the entire graph, regardless of the amount of data?

![device-2015-01-09-105408](https://cloud.githubusercontent.com/assets/2743647/5678636/cdbd099e-97f4-11e4-8e80-eb703574fb29.png)
![device-2015-01-09-105440](https://cloud.githubusercontent.com/assets/2743647/5678637/cdbd2104-97f4-11e4-88b2-9c836d78b1d4.png)

**Comment by ptrasatti** [comment]
Don,

   You need to set the X-Axis viewport with the 4.0.0 API.

See this page for more info...

http://www.android-graphview.org/documentation/category/all

Phil

// GraphView 4.x
// set manual X bounds
graph.getViewport().setXAxisBoundsManual(true);
graph.getViewport().setMinX(0);
graph.getViewport().setMaxX(5);

**Comment by jjoe64** [comment]
it's because graphview tries to make nice looking values and so it can happen that the viewport is a lit bigger than the data.
but as Phil already said you can set the bounds manual

**Comment by DonKamillo88** [comment]
thanks for the reply
Now it's working
