### ISSUE TITLE
Proposed fix for Graphview 4.0.0 scrolling/update issue when "scrollToEnd" option is enabled and manual viewport is set

### ISSUE THREAD

**Issue by ptrasatti** [jjoe64/GraphView#275]
Jonas,

I discovered an issue w/ 4.0.0 under the following conditions and came up with a fix for you to review. My app is a real-time chart that graphs remote sensors, appending the data to the chart and updating the viewport window to show the last n seconds of the chart. I allow the user to pause the updates and scroll the chart to see the data that's out of the current viewport.

Here are the conditions that cause the issue:

           1. mXAxisBoundsManual  is set to true and viewport is updated in real-time.
           2. Dynamically updating with appendData() & "scrollTEnd=true".
           3. mIsScrollable and mIsScalable are set to true.
           4. Scroll the screen with finger.

Issue: The grid and labels on the chart don't update correctly in this case because the pixel/scroll calculations in adjustHorizontal() are off due to mScrollingReferenceX never being cleared under these conditions.

I added a line of code to the scrollToEnd() routine in the Viewport class and tested the fix. It corrects the issue. 

                    mScrollingReferenceX = Float.NaN;   // *** PJT

Can you review my fix and fold it into the next GraphView release? 

Thanks,

Phil Trasatti
USA 

New version of scrollToEnd() routine:

    public void scrollToEnd() {
        if (mXAxisBoundsManual) {
            float size = mCurrentViewport.width();
            mCurrentViewport.right = mCompleteRange.right;
            mCurrentViewport.left = mCompleteRange.right - size;
            mScrollingReferenceX = Float.NaN;   // *** PJT
            mGraphView.onDataChanged(true, false);
        } else {
            Log.w("GraphView", "scrollToEnd works only with manual x axis bounds");
        }
    }

**Comment by jjoe64** [comment]
I will check asap. Thanks

**Comment by ptrasatti** [comment]
Thanks - Also, if I pinch the screen, the OnScaleEnd() routine resets mScrollingReferenceX  and this fixes the drawing issue. That's how I came up with the fix.

Phil
