### ISSUE TITLE
Position labels

### ISSUE THREAD

**Issue by dkovalkov** [jjoe64/GraphView#277]
I want position labels. Add some right padding for Y labels and top padding for X labels. How I can do that? Example on xxhdpi screen.
https://www.dropbox.com/s/zrdr143c8jn54k0/stat_screen.png?dl=0
lib version 4.0.0

**Comment by adiohaion** [comment]
excellent library, but this is really important, one my graph looks terribly bad becasue of this.

**Comment by jjoe64** [comment]
now there is a default spacing.
you can set your own parameter via getGridLabelRenderer().setLabelsSpace()

**Comment by dkovalkov** [comment]
Thank you for attention. I used to set label spacing to 20. And got different results for x and y axises.
![stat_screen-3](https://cloud.githubusercontent.com/assets/1046822/9235759/7776efa6-4149-11e5-96df-1b0492cd6070.png)
