### ISSUE TITLE
BarGraphSeries crash if there is a single column

### ISSUE THREAD

**Issue by ImAtanuki** [jjoe64/GraphView#281]
No issues on multiple columns, but one column is not accepted.

01-21 12:32:45.916    ................................ E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.ArithmeticException: divide by zero
            at com.jjoe64.graphview.series.BarGraphSeries.draw(BarGraphSeries.java:146)
            at com.jjoe64.graphview.GraphView.onDraw(GraphView.java:298)

In BarGraphSeries:
....
146           float colwidth = graphView.getGraphContentWidth() / (numOfBars-1);
....

**Comment by ralucagurau** [comment]
Hello joe , 

I have this crash and I downloaded the latest version 
  compile 'com.jjoe64:graphview:4.0.0'

**Comment by filipsisic** [comment]
Crash still exists, I have a BarGraphSeries with one DataPoint and it crashes every time.
