### ISSUE TITLE
Static Labels x-Axis(Horizantal) labels not displaying

### ISSUE THREAD

**Issue by vasireddyajay** [jjoe64/GraphView#285]
Hi,

I am using graphview 4.0.0. I want to set horizontal labels. How ever, I could see only vertical axis labels. Please guide.

BarGraphSeries<DataPoint> series = new BarGraphSeries<DataPoint>(
				new DataPoint[] { new DataPoint(1, 10), new DataPoint(2, 20),
						new DataPoint(3, 30), new DataPoint(4, 40),
						new DataPoint(5, 50), new DataPoint(6, 60),
						new DataPoint(7, 70), new DataPoint(8, 80),
						new DataPoint(9, 90), new DataPoint(10, 100),
						new DataPoint(11, 0) });

		// draw values on top
		series.setSpacing(50);
		series.setDrawValuesOnTop(true);
		series.setValuesOnTopColor(Color.RED);

		String[] horizanAxisNames = new String[] { "JAN", "FEB", "MAR", "APR",
				"MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC" };

		String[] verticAxisNames = new String[] { "0%", "10%", "20%", "30%",
				"40%", "50%", "60%", "70%", "80%", "90%", "100%" };

StaticLabelsFormatter staticLabels = new StaticLabelsFormatter(
				graphView, horizanAxisNames, verticAxisNames);
		graphView.getGridLabelRenderer().setLabelFormatter(staticLabels);
		graphView.getGridLabelRenderer().setNumHorizontalLabels(12); 
		graphView.getLegendRenderer().setTextColor(Color.BLACK);
		graphView.addSeries(series);

**Comment by jjoe64** [comment]
i will check...

**Comment by jjoe64** [comment]
your code works for me. maybe your view is not visible completely? reduce the height of graphview or use a scrolling parent view...

**Comment by vasireddyajay** [comment]
Thanks for the feedback and helping hand. In between, I moved to MPAndroidChartLibrary. Untill now, it seems to solve my challenges.
