### ISSUE TITLE
2 data points not displayed

### ISSUE THREAD

**Issue by jjoe64** [jjoe64/GraphView#287]
DataPoint[] prova = new DataPoint[2];
 
        prova[0] = new DataPoint(0, 1);
        System.out.println(prova[0].toString()); // [0.0/1.0]
        prova[1] = new DataPoint(1, 1);
        System.out.println(prova[1].toString()); // [1.0/1.0]
 
        // No Graph will be printed
        GraphView graph = (GraphView) findViewById(R.id.graph);
        LineGraphSeries<DataPoint> series = new LineGraphSeries<DataPoint>(prova);
        graph.addSeries(series);

**Comment by Ibbus93** [comment]
I've fixed the problem: it works only for API 14 and not for API 19
