### ISSUE TITLE
GraphView on Android Studio

### ISSUE THREAD

**Issue by davix10** [jjoe64/GraphView#288]
Hi, I can not load the library on android study also having followed the steps and still get this error: cannot resolve method. Please help me. Import only this "import com.jjoe64.graphview.GraphView;"

**Comment by jjoe64** [comment]
which method can not be resolved?

**Comment by davix10** [comment]
resetData, setViewPort and more

**Comment by ptrasatti** [comment]
It's working fine for me w/ Android Studio and Graphview 4.0.0.

Include one of these to resolve depending on the class you are using and it should resolve for you.
   import com.jjoe64.graphview.series.Series;
   import com.jjoe64.graphview.series.BaseSeries;
   import com.jjoe64.graphview.series.LineGraphSeries;
   import com.jjoe64.graphview.series.BarGraphSeries;
   import com.jjoe64.graphview.series.PointGraphSeries;

Phil

**Comment by davix10** [comment]
import com.jjoe64.graphview.BarGraphView;  -------> cannot resolve symbol 'BarGraphView' 

I have this

**Comment by ptrasatti** [comment]
You forgot ".series" in the import statement,
It's  "import com.jjoe64.graphview.series.BarGraphSeries" 

NOT "import com.jjoe64.graphview.BarGraphSeries"

Phil

**Comment by davix10** [comment]
I have always errors here resetData

**Comment by jjoe64** [comment]
are you sure you use the current version of GraphView?
please check your dependency in Gradle file and check your code
clean / rebuild all, reload gradle etc...
it's not a bug of graphview

**Comment by davix10** [comment]
compile 'com.jjoe64:graphview:4.0.0' is in the gradle

**Comment by ptrasatti** [comment]
Here's the code... everything works fine if the right imports are used.

Phil

import com.jjoe64.graphview.GraphView;
import com.jjoe64.graphview.series.BarGraphSeries;

{
                DataPoint[] dp = {new DataPoint(0,0), new DataPoint(1,1), new DataPoint(2,2)};
                BarGraphSeries barGraphSeries = new BarGraphSeries(dp);

                ...

                barGraphSeries.resetData(dp);
}

**Comment by jjoe64** [comment]
@davix10 please show your code if it is till not working

**Comment by davix10** [comment]
This is my code:
findViewById(R.id.Graph).setVisibility(View.VISIBLE);
							if (isFloatNumber(prova)){

								if(relative==false)
								{

									Series.resetData(new GraphViewData[] {
											new GraphViewData(1,risultato)

									});
									tresh1.resetData(new GraphViewData[] {

											new GraphViewData(2,0)
									});
									range1.resetData(new GraphViewData[] {
											new GraphViewData(3,0)

									});


								}

**Comment by davix10** [comment]
I get the error already here: static GraphViewSeries range1, range2, range3, range4

**Comment by jjoe64** [comment]
show your imports

**Comment by davix10** [comment]
import com.jjoe64.graphview.series.Series;
import com.jjoe64.graphview.series.BaseSeries;
import com.jjoe64.graphview.series.LineGraphSeries;
import com.jjoe64.graphview.series.BarGraphSeries;
import com.jjoe64.graphview.GraphView;

**Comment by jjoe64** [comment]
and there is no errors on that import lines?

**Comment by davix10** [comment]
no

**Comment by osamaastal** [comment]
***** I tried all of these, but it can't resolve symbol "jjoe64" !!! *****

import com.jjoe64.graphview.series.Series;
import com.jjoe64.graphview.series.BaseSeries;
import com.jjoe64.graphview.series.LineGraphSeries;
import com.jjoe64.graphview.series.BarGraphSeries;
import com.jjoe64.graphview.GraphView;

**Comment by royseberg** [comment]
On a similar note, with implementation ...  4.2.2  I get errors on the following:
import com.jjoe64.graphview.GraphViewSeries;
import com.jjoe64.graphview.LineGraphView;
