### ISSUE TITLE
The Y axis labels doesn't update when appending data in real-time scenario

### ISSUE THREAD

**Issue by pdaddy26** [jjoe64/GraphView#289]
Hi, 

I have just started experimenting with your great chart library. I'm particularly interested in using in real-time scenario, updating it every second. I notice that the Y labels doesn't update when the values changes. For example, I have values 70, 70, 68 ... the Y values starts from 68 to 70 .. but then I have 66 .. the Y values remains 68 to 70 ....

Thanks,

**Comment by jjoe64** [comment]
that's because the viewport does a rounding that the numbers are nice to look at. you could set the viewport as you want after changing your data

**Comment by pdaddy26** [comment]
Can you provide a code example please? I dont quite understand your answer. To me it sounds like a bug. Since it provides a way to append data to the series but the y axis label doesnt update to match the new min and max values.

**Comment by jjoe64** [comment]
oh my fault. yes this sounds like a bug. I will check it

**Comment by jjoe64** [comment]
in the realtime example of graphview-demos it's working correctly. do you set a the y-bounds or labels manually?
can you provide a code where it can be reproduced?

**Comment by pdaddy26** [comment]
Here is an example: https://dl.dropboxusercontent.com/u/33918766/GraphView.zip

I don't set the y-bounds manually, all I do is use the appendData.

**Comment by jjoe64** [comment]
2 points:
1) this code does not change anything, because scrollToEnd Parameter only works with manual x bound
2) when I set scrollToEnd=false then it works and the y labels changes when the data increases
