### ISSUE TITLE
The Y axis labels width not correct when it has decimals

### ISSUE THREAD

**Issue by pdaddy26** [jjoe64/GraphView#290]
Hi, 

I have a chart that has decimals values from 0 to 5 and the chart renders the Y label width incorrectly. 

![screen shot 2015-02-10 at 12 22 25 am](https://cloud.githubusercontent.com/assets/10935411/6121997/ee41101e-b0ba-11e4-8296-816756f87b61.png)

I suppose it is supposed to be 0, 1.25, 2.5, 3.75, 5

Thanks,

**Comment by jjoe64** [comment]
because of performance reasons, it will not check every label to fit.
=> TODO manual set of labels setLabelVerticalWidth/setLabelHorizontalHeight
