### ISSUE TITLE
The method addSeries(Series) in the type GraphView is not applicable for the arguments (GraphViewSeries)?

### ISSUE THREAD

**Issue by Berg230481** [jjoe64/GraphView#294]
My imports

import com.jjoe64.graphview.GraphView;
import com.jjoe64.graphview.GraphViewData;
import com.jjoe64.graphview.GraphViewDataInterface;
import com.jjoe64.graphview.GraphViewSeries;
import com.jjoe64.graphview.GraphViewSeries.GraphViewSeriesStyle;
import com.jjoe64.graphview.LineGraphView;
import com.jjoe64.graphview.series.Series;

My Problem
The method addSeries(Series) in the type GraphView is not applicable for the arguments (GraphViewSeries)

youre solve?

**Comment by jjoe64** [comment]
i think you have mixed graphview 4.0 with 3.x
check your libs and dependencies
