### ISSUE TITLE
GraphView doesn't update correctly if parent layout changes size

### ISSUE THREAD

**Issue by oinegue** [jjoe64/GraphView#297]
If you have a GraphView in a Layout, say LinearLayout, that changes size during runtime, the lines and labels in the graph get all wrong positioned.

I think the problem is in this line: https://github.com/jjoe64/GraphView/blob/master/src/main/java/com/jjoe64/graphview/GraphView.java#L364

Comments say that it "Will recalculate the viewport and labels", but calling `onDataChanged(true, true);` keep their size instead of recalculating.

**Comment by jjoe64** [comment]
good hint
i will check
