### ISSUE TITLE
why double d= Double.valueOf(String) dont run

### ISSUE THREAD

**Issue by Berg230481** [jjoe64/GraphView#300]
Problem:

I have a ArrayList<string> an i filter with substring this what i want,
but GraphViewDataInterface accept only Doubel?

  mTimer2 = new Runnable() {
            @Override
            public void run() {
                exampleSeries.resetData(new GraphViewData[] {
                		
                		new GraphViewData(PROBLEM,getRandomTy()), 
                		
                });

whats can i do?

thy

**Comment by jjoe64** [comment]
i think this is a general java understanding problem for you. of course you have to fill the data with numbers (double) so you have to convert your strings
