### ISSUE TITLE
crash if used with getSecondScale() and setBackgroundColor()

### ISSUE THREAD

**Issue by hmueller01** [jjoe64/GraphView#304]
I have taken the sample code form Second Y Axis and added the last line (`graph.getViewport().setBackgroundColor(...)`).

    GraphView graph = (GraphView) findViewById(R.id.graph);
    LineGraphSeries<DataPoint> series1 = new LineGraphSeries<DataPoint>(new DataPoint[] {
                new DataPoint(0, 1),
                new DataPoint(1, 5),
                new DataPoint(2, 3),
                new DataPoint(3, 2),
                new DataPoint(4, 6)
        });
        graph.addSeries(series1);

        LineGraphSeries<DataPoint> series2 = new LineGraphSeries<DataPoint>(new DataPoint[] {
                new DataPoint(0, 30),
                new DataPoint(1, 30),
                new DataPoint(2, 60),
                new DataPoint(3, 20),
                new DataPoint(4, 50)
        });

        // set second scale
        graph.getSecondScale().addSeries(series2);
        // the y bounds are always manual for second scale
        graph.getSecondScale().setMinY(0);
        graph.getSecondScale().setMaxY(100);
        series2.setColor(Color.RED);
        graph.getGridLabelRenderer().setVerticalLabelsSecondScaleColor(Color.RED);

        // legend
        series1.setTitle("foo");
        series2.setTitle("bar");
        graph.getLegendRenderer().setVisible(true);
        graph.getLegendRenderer().setAlign(LegendRenderer.LegendAlign.TOP);
        
        graph.getViewport().setBackgroundColor(Color.argb(255, 222, 222, 222));

Compiles, but throws java.lang.NullPointerException at com.jjoe64.graphview.GridLabelRenderer.getLabelVerticalSecondScaleWidth(GridLabelRenderer.java:1365)

I use the latest GraphView cloned from github ...

Holger

**Comment by jjoe64** [comment]
thanks for reporting

**Comment by hmueller01** [comment]
Fix worked. Thanks.
