### ISSUE TITLE
Line Graph with Circles on the joints and Y value, and limit the max value at X and Y axis

### ISSUE THREAD

**Issue by vyscond** [jjoe64/GraphView#306]
Hey guys, probably it's on their messy compact documentation about customization but i can't find it.

So i want to create a chart like this on the below picture, but the joints are replaced with circle. and i need to show only the Y axis value over on top of every joint. Any help? Thanks :+1: 

![line chart](http://www.indiabix.com/_files/images/data-interpretation/line-charts/15-3-10-1.png)

**Comment by jjoe64** [comment]
currently values can only be drawn on top of bar chart.

**Comment by jjoe64** [comment]
#307
