### ISSUE TITLE
getSecondScale().setMinY() and  getSecondScale().setMaxY() ignored if using a staticLabelsFormatter for the primary series

### ISSUE THREAD

**Issue by arober11** [jjoe64/GraphView#308]
If I use a StaticLabelsFormatter for the primary series labels I'm unable to set a different secondScale() set of labels. The graph is rendered with the static Y labels on both sides. 

Appears the getSecondScale().setMinY() and  getSecondScale().setMaxY() values are ignored if a graphView.getGridLabelRenderer().setLabelFormatter(staticLabelsFormatter) for the primary series.  

Either need the StaticLabelsFormatter() code tweaked to allow you to ALSO manually set the secondScale labels, and / or for the graphView.getGridLabelRenderer() code to only apply the  StaticLabelsFormatter to the primary series, so any secondScale() values are rendered.

Example code.

        StaticLabelsFormatter staticLabelsFormatter = new StaticLabelsFormatter(graphView);
        staticLabelsFormatter.setHorizontalLabels(new String[] {"AA","BB","CC","DD","EE"});
        staticLabelsFormatter.setVerticalLabels(new String[] {"aa","bb","cc","dd","ee"} );

...
        PointsGraphSeries<DataPoint> series3 = new PointsGraphSeries<DataPoint>(new DataPoint[] {
                new DataPoint(0, 0),
                new DataPoint(1, 3),
                new DataPoint(2, 1),
                new DataPoint(3, 0),
                new DataPoint(4, 4)
        });
        series3.setShape(PointsGraphSeries.Shape.TRIANGLE);
        series3.setColor(Color.YELLOW);

        LineGraphSeries<DataPoint> series2 = new LineGraphSeries<DataPoint>(new DataPoint[] {
                new DataPoint(0, -1),
                new DataPoint(1, 4),
                new DataPoint(2, 2),
                new DataPoint(3, 1),
                new DataPoint(4, 5)
        });
        series2.setColor(Color.RED);

        graphView.addSeries(series3);
        graphView.getGridLabelRenderer().setNumVerticalLabels(5);
        graphView.getGridLabelRenderer().setLabelFormatter(staticLabelsFormatter);

        // set second scale
        graphView.getSecondScale().addSeries(series2);
        // the y bounds are always manual for second scale
        graphView.getSecondScale().setMinY(-2);
        graphView.getSecondScale().setMaxY(6);
        graphView.getGridLabelRenderer().setVerticalLabelsSecondScaleColor(Color.RED);
        graphView.addSeries(series2);

**Comment by jjoe64** [comment]
thanks for reporting
