### ISSUE TITLE
GraphView No Horizontal Labels

### ISSUE THREAD

**Issue by hydrophylic** [jjoe64/GraphView#309]
Hello- 
I am new to GitHub, but I am trying to use GraphView 4.0 for an app and for some reason the horizontal labels do not display.  Below is the code I am using:

GraphView graph = (GraphView) chrtView.findViewById(R.id.graph);
        LineGraphSeries<DataPoint> series = new LineGraphSeries<DataPoint>(new DataPoint[] {
                new DataPoint(0, 1),
                new DataPoint(1, 5),
                new DataPoint(2, 3),
                new DataPoint(3, 2),
                new DataPoint(4, 6)
        });
        graph.addSeries(series);

And the following XML which is imbedded in a linear layout.

        <com.jjoe64.graphview.GraphView
        android:layout_width="match_parent"
        android:layout_height="200dip"
        android:id="@+id/graph" />

I am not including the .jar file in my library folder but instead include the following statement with my dependencies in my build.gradle: 

compile 'com.jjoe64:graphview:4.0.0'

This is basically the exact code that included in the documentation.  Doe anyone have any suggestions what I might be doing incorrectly?

thanks.

**Comment by jjoe64** [comment]
i can not reproduce it. maybe you can upload a small android project with this problem so i can debug

**Comment by hydrophylic** [comment]
Hi Jonas -

Sorry for the late reply and thank you for your response.  I'm a GitHub
newby and I do not know how to upload an android project.  Let me do some
research on this so I can get project uploaded for you.

Sorry!

Chris

**Comment by hydrophylic** [comment]
Hi Jonas -

I just tried my test application on a device instead of an AVD and the
horizontal labels worked.  The AVD I was using that I was having issues
with horizontal labels was the Nexus S, API 21,  Google API, and "Store a
snapshot for faster startup" checked.  Maybe I just need to set up a new
AVD.  Anyhow just thought I'd give you the update.

Thanks,
Chris

**Comment by jjoe64** [comment]
any news on this? because I tested the demo project with AVD Nexus S (21) and I there were no issues...

**Comment by jjoe64** [comment]
there is also now the possibility to set the height of the horizontal labels manually via setLabelHorizontalHeight

**Comment by hydrophylic** [comment]
Hi Jonas -

I will try again.  I've been developing this android app as a side project
and the last 3 weeks my primary job has been demanding all of my free
time.  I will be looking at this closer next week because I should have
more time.  Sorry for the delay and thanks for your attention to the issue.

Chris

**Comment by mile-janev** [comment]
Weird, I was having the same problem but with Nexus 4 API 15, then switched to Nexus S, API 21 and horizontal labels were here.

**Comment by jjoe64** [comment]
i also tried with api 15 and no problems with the grapview-demos app.
can anybody provide a complete project where i can reproduce it?

**Comment by hydrophylic** [comment]
Hi Jonas -

So sorry for getting to this so late.  What is the best way to get you a
complete project?  Would you like me to create a repository on github.
Anyhow I apologize for the ignorance.  I am completely new to github.

Thanks,
Chris

**Comment by jjoe64** [comment]
github or share it as zip here or on dropbox etc....

**Comment by hydrophylic** [comment]
Hi Jonas -

Sorry for the delay, but I realize that I ran into this issue before.  I
cannot attached a zipped Android Studio project to gmail.  I was able to
zip projects with Eclipse but since I recently switched to Android Studio
and it does not have this capability.  I also looked into sharing it on git
and I really can't make heads or tails how to do this either.  When I try
to use the VCS menu to share a project on github I get an error that it
cannot find git.exe.  In my settings of Android Studio I tried to map the
location of git.exe but I can't find it anywhere.  Anyhow I would love to
share this project with you but I'm pulling my hair out right now and on
how to do this.  Sorry!  I'll try again later when I have more time.

Thanks,

Chris

**Comment by hydrophylic** [comment]
Hi Jonas -

I added you as a contributor to the repository where I added the project.
It is called "GraphView4Check".  Anyhow let me know if you have any issues
accessing this or if you have any questions.

Thanks,
Chris

**Comment by jjoe64** [comment]
thanks a lot i will test

**Comment by jjoe64** [comment]
@hydrophylic 
Hi Chris, for me the project works perfectly. Which Android version do you have? Which device or simulator? I really want to see the problem with the missing labels...

**Comment by hydrophylic** [comment]
Hi Jonas -

I was using Nexus S AVD with Android 5 and API 21, Google APIs target, and
x86 CPU.  When I ran it on my personal device which is a Samsung GS4 with
Android 4.4.2 the labels worked fine.  Anyhow good luck and let me know if
you have any more questions.

Chris

**Comment by jjoe64** [comment]
your test project is working for me with nexus s avd API 21 x86 image
i have no clue what i can do anymore...

**Comment by hydrophylic** [comment]
Hi Jonas - Thanks for looking into this. It's good you could not replicate
the issue.  As I mentioned in a previous post I was not able to replicate
this issue with my personal device, buy only occurs on the AVD.  It must be
a very isolated issue.

Chris
