### ISSUE TITLE
 graphView.getLegendRenderer().setAlign(BOTTOM);

### ISSUE THREAD

**Issue by arober11** [jjoe64/GraphView#311]
The majority legend box is rendered below the Graph / off screen, when setAlign(BOTTOM) is used.
![screen shot 2015-03-01 at 17 39 34](https://cloud.githubusercontent.com/assets/1850542/6432030/f9adcba6-c03a-11e4-9225-2012d724f5e1.png)

**Comment by jjoe64** [comment]
thanks for report

**Comment by arober11** [comment]
Thanks
