### ISSUE TITLE
X-axis not fully used

### ISSUE THREAD

**Issue by mdbigg** [jjoe64/GraphView#312]
Hi,

I was using GraphView 3 without a problem but have started trying to use 4. I'm generating a line graph of various values, given by date on the X axis. However, only about half of the X axis is actually used (see screenshot). In GraphView 3 it spread the X axis out to use the whole space, but GV4 doesn't seem to. Any ideas? Is there something I need to add for this to happen?

Thanks!

            DataPoint[] dataKbIsa = new DataPoint[this.histories.size()];
            DataPoint[] dataMbIsa = new DataPoint[this.histories.size()];
            DataPoint[] dataPortfolio = new DataPoint[this.histories.size()];
            DataPoint[] dataTotal = new DataPoint[this.histories.size()];

            long unixTime;
            ValueHistory history;
            Log.d(TAG, "Looping histories (" + Integer.toString(this.histories.size()) + ")");
            for (int i=0; i<this.histories.size(); i++) {
                history = histories.get(i);
                history.prepareForDisplay();
                unixTime = history.dateToTimestamp();
                dataMbIsa[i] = new DataPoint(unixTime, history.mbIsaValue.floatValue());
                dataKbIsa[i] = new DataPoint(unixTime, history.kbIsaValue.floatValue());
                dataPortfolio[i] = new DataPoint(unixTime, history.portfolioValue.floatValue());
                dataTotal[i] = new DataPoint(unixTime, history.totalValue.floatValue());
            }

            LineGraphSeries<DataPoint> seriesMbIsa = new LineGraphSeries<DataPoint>(dataMbIsa);
            LineGraphSeries<DataPoint> seriesKbIsa =new LineGraphSeries<DataPoint>(dataKbIsa);
            LineGraphSeries<DataPoint> seriesPortfolio = new LineGraphSeries<DataPoint>(dataPortfolio);
            LineGraphSeries<DataPoint> seriesTotal = new LineGraphSeries<DataPoint>(dataTotal);

            seriesMbIsa.setTitle("MB ISA");
            seriesMbIsa.setColor(Color.BLUE);
            seriesKbIsa.setTitle("KB ISA");
            seriesKbIsa.setColor(Color.RED);
            seriesPortfolio.setTitle("Portfolio");
            seriesPortfolio.setColor(Color.GREEN);
            seriesTotal.setTitle("Total");
            seriesTotal.setColor(Color.BLACK);

            final java.text.DateFormat dateTimeFormatter = DateFormat.getDateFormat(this.context);

            GraphView graphView = new GraphView(this.context);
            graphView.getGridLabelRenderer().setLabelFormatter(new DefaultLabelFormatter() {
                @Override
                public String formatLabel(double value, boolean isValueX)
                {
                    if (isValueX)
                    {
                        return dateTimeFormatter.format(new Date((long) value*1000));
                    } else {
                        return "£" + super.formatLabel(value, isValueX);
                    }

                }
            });

            graphView.addSeries(seriesTotal);
            graphView.addSeries(seriesPortfolio);
            graphView.addSeries(seriesKbIsa);
            graphView.addSeries(seriesMbIsa);

            // Formatting
            graphView.getLegendRenderer().setVisible(true);

            graphView.getViewport().setScrollable(true);
            graphView.getViewport().setScalable(true);
            graphView.getGridLabelRenderer().setVerticalLabelsVisible(true);
            graphView.getGridLabelRenderer().setHorizontalLabelsVisible(true);

            graphView.getGridLabelRenderer().setGridColor(Color.BLACK);
            graphView.getGridLabelRenderer().setHorizontalLabelsColor(Color.BLACK);
            graphView.getGridLabelRenderer().setVerticalLabelsColor(Color.BLACK);

            LinearLayout layout = (LinearLayout) findViewById(R.id.graphLayout);
            layout.addView(graphView);

![image](https://cloud.githubusercontent.com/assets/11074899/6472255/f1f3aa8e-c1e8-11e4-80e6-f195c0c150c0.png)

**Comment by mdbigg** [comment]
I've fixed this by manually setting X-axis bounds:

            graphView.getViewport().setXAxisBoundsManual(true);
            graphView.getViewport().setMinX(histories.get(0).dateToTimestamp());
            graphView.getViewport().setMaxX(histories.get(histories.size()-1).dateToTimestamp());

**Comment by jjoe64** [comment]
yes that's because GV4 now tries to make a viewport with "nice" round numbers (e.g. 0, 5, 10, 15) to avoid floating numbers.

Manual Bound can be a solution

**Comment by mdbigg** [comment]
Could there be an option that sets bounds more precisely? 
getViewPort.setPreciseBounds(true)?

I can understand the desire to use nice round numbers but there must be 
lost of scenarios in which they are not (for example, my graph which 
uses timestamps converted to dates).
