### ISSUE TITLE
Zooming doesnt work at all 

### ISSUE THREAD

**Issue by mynavy** [jjoe64/GraphView#315]
On the previous version of GraphView 3.x I have been able to zoom perfectly. 
Now when im trying the same graph on GraphView 4.0.0 it does not zoom at all. 

I added those lines: 
graph.getViewport().setScalable(true);
graph.getViewport().setScrollable(true);

but nothing happens.
However, when im adding those lines also:
graph.getViewport().setXAxisBoundsManual(true);
graph.getViewport().setYAxisBoundsManual(true);

The situation gets better but still zooming is not smoothly at all. 

Any ideas what im doing wrong? 
Thanks.

**Comment by jjoe64** [comment]
=> check if it works without setting manual bounds
