### ISSUE TITLE
Horizontal axis labels not visible

### ISSUE THREAD

**Issue by jhavelik** [jjoe64/GraphView#316]
Hi,
I have a problem with new version (4.0) of graphview. I'm tring to display horizontal labels on my line graph and it's not working. Below is code snippet of creating graph and screenshot of created graph.

// initialize graph
GraphView graph = new GraphView(view.getContext());
//init legend
graph.getLegendRenderer().setVisible(true);
graph.getLegendRenderer().setWidth(200);
graph.getLegendRenderer().setAlign(LegendAlign.MIDDLE);
graph.getLegendRenderer().setTextSize(30);
graph.getLegendRenderer().setSpacing(10);
//set grid and labels
graph.getGridLabelRenderer().setGridColor(Color.WHITE);
		
graph.getGridLabelRenderer().setVerticalLabelsColor(Color.WHITE);		
		
graph.getGridLabelRenderer().setHorizontalLabelsVisible(true);
graph.getGridLabelRenderer().setHorizontalLabelsColor(Color.WHITE);
//set static labels of x axis
StaticLabelsFormatter staticLabelsFormatter = new StaticLabelsFormatter(graph);
staticLabelsFormatter.setHorizontalLabels(new String []{"1", "2", "3","4", "5"});
graph.getGridLabelRenderer().setLabelFormatter(staticLabelsFormatter);
// add data
for (int i = 0; i < series.length; i++) {
	graph.addSeries(series[i]);
}

![Graph](http://s2.postimg.org/pjp3k22i1/Screenshot_2015_03_10_12_21_50.jpg)

Labels aren't displayed even when i do not use static labels. Layout where is graph placed has bottom padding so it should not be covered by anything else...
Also first data point is not highlighted by dot using code below why?

series.setDrawDataPoints(true);
series.setDataPointsRadius(4f);

Is there any way to make data points solid? Not just borders?

Thanks for answers...

**Comment by jjoe64** [comment]
can you please give me your layout.xml and also which android version are you using?

**Comment by jjoe64** [comment]
duplicate #309

**Comment by gptshubham595** [comment]
also sometimes this line make this issue 
On removing this everything works perfectly
android:hardwareAccelerated="false"
