### ISSUE TITLE
segment horizontally by year endpoints

### ISSUE THREAD

**Issue by bdols** [jjoe64/GraphView#317]
would be a nice feature to drop the horizontal lines between the data points for 12-31-LAST_YEAR and 01-01-CURRENT_YEAR

**Comment by jjoe64** [comment]
what exactly do you mean?

**Comment by bdols** [comment]
With DateAsXAxisLabelFormatter formatting the x-axes nicely, instead of splitting the lines evenly
when I graph points that stretch from April 2005 to April 2015, I'd like to have the lines at January 2015, January 2014, January 2013, etc.

I set NumHorizontalLabels to 12 for 10 year graph to get a x-axes line every year. Would be nice to have another way to segment dates by year endpoints.

**Comment by jjoe64** [comment]
i think thats too specific
