### ISSUE TITLE
How to dynamically set view port minY and maxY values in real time mode?

### ISSUE THREAD

**Issue by ntoskrnl** [jjoe64/GraphView#321]
On previous version, all I had to do is to override `getMin()` and `getMax()` methods `GraphView`.
All the time I append new data points to the graph, I need to update min and max according to some rule. How do I do this now?

Thank you.

**Comment by jjoe64** [comment]
there are methods for this e.g.
mgraph.getViewport().setMinY()

also set manual viewport before via:
getViewport().setYAxisBoundsManual(true)
