### ISSUE TITLE
scaling out past maxX does not 'fit to maxX'

### ISSUE THREAD

**Issue by abeatte** [jjoe64/GraphView#322]
I have a large dataset. 
I viewport.scrollToEnd().
I then pinch to zoom-in. 

I see an empty section on the right where the viewport has exceeded the maxX. 

I believe the issue lies somewhere in Viewport.java (maybe near lines 45-54).

**Comment by abeatte** [comment]
@jjoe64, any movement on this one. I am curious as to what the bug really was?

**Comment by jjoe64** [comment]
this is a bug, i know it. I will fix this the next few days...

**Comment by jjoe64** [comment]
it's because the after a zooming the viewport bounds will be reseted to nice rounding numbers (e.g. 0, 50, 100, 150, 200). then it can happen that there will be space after the last data point.

**Comment by jjoe64** [comment]
#328

**Comment by abeatte** [comment]
![screenshot 2015-05-05 08 01 50](https://cloud.githubusercontent.com/assets/2646229/7475534/05d301e0-f2fd-11e4-80ec-65778ecb9925.png)

I am still able to reproduce this bug.

**Comment by abeatte** [comment]
@jjoe64, can we reopen this?
