### ISSUE TITLE
Bug with iterater (causes app crashes in my implementation)

### ISSUE THREAD

**Issue by HylkeB** [jjoe64/GraphView#323]
Theres a bug, and i would make a pull request if i knew how it worked and if i used gradle, but since i dont, and the bug fix is only 21 chars long ill just post it here.

The issue is an unhandled nullpointer exception in BaseSeries.java

Lines 177 to 185 are originally:
```Java
...
// go to first
boolean found = false;
E prevValue = null;
if (org.hasNext()) {
   prevValue = org.next();
}
if (prevValue.getX() >= from) {
   nextValue = prevValue;
   found = true;
...
```

and should be 
```Java
...
// go to first
boolean found = false;
E prevValue = null;
if (org.hasNext()) {
   prevValue = org.next();
}
if (prevValue != null && prevValue.getX() >= from) {
   nextValue = prevValue;
   found = true;
...
```

Its all about the 
```Java
prevValue != null && 
```

I hope someone can fix it.

**Comment by jjoe64** [comment]
no that's not a bug. It's not allowed to use null-pointer within the data array, because that can cause trouble on other places in the code. you should fix this on the app-side code
