### ISSUE TITLE
Different color for different point

### ISSUE THREAD

**Issue by zak84** [jjoe64/GraphView#324]
I've downloaded android-graphview which is a great library, but I think it have a missing features (which i need). I need to set different color for different point, in a LineGraphSeries. I can only set color for line and background...
so i need something like new DataPoint(x,y,color).
there's a way?

**Comment by jjoe64** [comment]
you could use a (second) series "PointsGraphSeries". There you have the option to use a CustomShape and then it is complete to you how to draw the single data points.
