### ISSUE TITLE
GraphView not being displayed when all DataPoints are 0.

### ISSUE THREAD

**Issue by RemcoEerden** [jjoe64/GraphView#330]
Hi,

I'm using the jjoe64 GraphView for my Android application, which works great! Currently i've got an issue with displaying the graph. When all DataPoint values are 0, the graph is not visible. The title is visible though. If I change one single value to 1 for example, it works fine. Does somebody know how to fix this?

Thanks, Remco

**Comment by jjoe64** [comment]
i will check. but i think this is already fixed in the github version which will be released soon

**Comment by jjoe64** [comment]
it's already fixed

**Comment by RemcoEerden** [comment]
Thanks! When is version 4.01 being released?

**Comment by jjoe64** [comment]
in the next week
