### ISSUE TITLE
Cannot resolve symbol addSeries(series)

### ISSUE THREAD

**Issue by Senemix29** [jjoe64/GraphView#333]
Hi,
Can you tell me why i got some error in this line?
graph.addSeries(series);

it says "Cannot resolve symbol"

i'm using Android Studio and i follwed this steps:
Option #1: Android Studio / Gradle
This is the recommended way if you use Android Studio / Gradle. You can require the library from the Maven Central Repository.
Add that line to your build.grade file into the dependencies block:
compile 'com.jjoe64:graphview:4.0.0'

And then, i follow this :
http://www.android-graphview.org/documentation/how-to-create-a-simple-graph

Could you please, help me ?

**Comment by jjoe64** [comment]
did you import the packages
com.jjoe64.graphview.GraphView
etc.

**Comment by Senemix29** [comment]
Yes,
Here is some of my imports:
import com.jjoe64.graphview.GraphView;
import com.jjoe64.graphview.series.DataPoint;
import com.jjoe64.graphview.series.LineGraphSeries;
import com.jjoe64.graphview.series.Series;

**Comment by jjoe64** [comment]
and is the line with the imports marked as error?
try clean, rebuild, re-import gradle etc.

**Comment by jasongqueen** [comment]
"graph.addSeries(series);" seems to cause my app to crash? comment it out and the app works fine? whats fix?

**Comment by Senemix29** [comment]
I finally solved the mystery. I put the code into the wrong place. Instead of create a function or a method and call him inside onCreate, i put the code outside of onCreate method.

@jasongqueen Try put the code inside the onCreate, this may fix the problem.
Thx for the help, anyway.

**Comment by shreyas-7** [comment]
@Senemix29 Why was it necessary for the code to be put in onCreate? I tried but couldn't find the answer

**Comment by royseberg** [comment]
I added these imports to make the     addSeries(series)     error disappear:
import com.jjoe64.graphview.GraphView;
import com.jjoe64.graphview.series.DataPoint;
import com.jjoe64.graphview.series.LineGraphSeries;
