### ISSUE TITLE
Set grid color

### ISSUE THREAD

**Issue by davix10** [jjoe64/GraphView#337]
Hi, I updated the library but no longer works command to color the grid. It remains the default color.
I had the version 4.0.0 and I switched to version 4.0.1.
Thanks in advance.

**Comment by pmarquez** [comment]
Same issue with me, just that I am not upgrading, 4.0.1 is the first version I have ever used.

**Comment by yuxingxin** [comment]
The same issue happend to me ,and I find call `reloadStyles()` can solve this issue;

**Comment by davix10** [comment]
Thanks a lot!

**Comment by ClementOlutola** [comment]
He means resetStyles().

**Comment by powerlinuxer** [comment]
yuxingxin's workaround worked pretty well. Appreciated!

In jjoe64.graphview.series.GridLabelRenderer.java,

/**
     * @param gridColor the color of the grid lines
     */
    public void setGridColor(int gridColor) {

        mStyles.gridColor = gridColor;
        reloadStyles();
    }

**Comment by dkovalkov** [comment]
I can't set labels text size. reloadStyles() is a workaround.
