### ISSUE TITLE
Incorrect y axis values

### ISSUE THREAD

**Issue by davix10** [jjoe64/GraphView#341]
Hi, I do not understand why the values of the y axis is incorrect. I enclose a picture of the graph:

![screenshot_2015-05-06-09-29-05](https://cloud.githubusercontent.com/assets/6436570/7489104/6098ca5c-f3d3-11e4-9fbb-6e58e122d74f.png)

The problem is the division of the number 3, it is 1.5 and not 2.
Thanks

**Comment by jjoe64** [comment]
i dont understand your problem. can you please give more information/code?

**Comment by davix10** [comment]
The event of my button that creates this problem is here:

case R.id.bYminus:
                if (view_port > 4) {
                    view_port = view_port / 2.0;
                    graphView.getViewport().setMinY(-view_port);
                    graphView.getViewport().setMaxY(view_port);
                }
                break;

In the graph is marked number 2 but it really would be 1.5.

**Comment by jjoe64** [comment]
please try with latest version and reopen issue if exists
