### ISSUE TITLE
Set X  labels with Date, it may  cause loss of accuracy.

### ISSUE THREAD

**Issue by zhouyu0615** [jjoe64/GraphView#342]
First ,thank you! You code do me a great help.
In the process of my code,I found a bug in set X labels with date.when X labels time interval is less 10 seconds, it can't  get a good graph. 
   Then I download the source code ,I found the reason is in Viewport.java function void calcCompleteRange. ,when change Double type X labels  values to Float type  Rect's  right param. 

     public void calcCompleteRange() {
         List<Series> series = mGraphView.getSeries();
         mCompleteRange.set(0, 0, 0, 0);
          if (!series.isEmpty() && !series.get(0).isEmpty()) {
            double d = series.get(0).getLowestValueX();
            for (Series s : series) {
                if (!s.isEmpty() && d > s.getLowestValueX()) {
                    d = s.getLowestValueX();
                }
            }
             mCompleteRange.left =(float) d;
             d = series.get(0).getHighestValueX();
            for (Series s : series) {
                if (!s.isEmpty() && d < s.getHighestValueX()) {
                    d = s.getHighestValueX();
                }
            }
            mCompleteRange.right = (float) d;
           .....
}

The date is timeMills value,it is too large,when the time interval is small,when cast double d to    double mCompleteRange.right/left.  it will cause  accuracy loss. it result the mCompleteRange.right==mCompleteRange.left  is true.   

I think to solve the problem is to buid a Double type parameter  BigRect class to repalce the Rect.

Because  in my project ,I only need the Hour,Minute,Second, my temporary solotion is  make a my date and a my DefaultLabelFormatter to meet my project need.

For temporary reference.

Like as follows :+1: 

       private double getDateX() {
		// 获得系统的时间，单位为毫秒,转换为妙
		long totalMilliSeconds = System.currentTimeMillis();
		long totalSeconds = totalMilliSeconds / 1000;

		// 求出现在的秒
		long currentSecond = totalSeconds % 60;

		// 求出现在的分
		long totalMinutes = totalSeconds / 60;
		long currentMinute = totalMinutes % 60;

		// 求出现在的小时
		long totalHour = totalMinutes / 60;
		totalHour=totalHour+8; //中国时区的偏移
		long currentHour = totalHour % 24;

		double myTime = currentSecond + currentMinute * 60 + currentHour * 60
				* 60;

		return myTime;

	}

      graphView1.getGridLabelRenderer()
     .setLabelFormatter(new DefaultLabelFormatter() {
					@Override
		public String formatLabel(double value, boolean isValueX) {
                       if (isValueX) {
					long totalSeconds = new Double(value).longValue();
					long currentSecond = totalSeconds % 60;

					long totalMinutes = totalSeconds / 60;
					long currentMinute = totalMinutes % 60;

					long totalHour = totalMinutes / 60;
					long currentHour = totalHour % 24;

				return String.format("%d:%d:%d", currentHour,
									currentMinute, currentSecond);
						} else {
							return super.formatLabel(value, isValueX);
						}

				}
		});

**Comment by HormCZ** [comment]
@zhouyu0615 I edited your code. This code takes time from the device so time zones aren't problem. The second edit is about formating time. Sometimes you can get for example 18:8:3 and this format is wrong so now the format is 18:08:03. 

Here is the Label formatter: 

        graph.getGridLabelRenderer().setLabelFormatter(new DefaultLabelFormatter() {
            @Override
            public String formatLabel(double value, boolean isValueX) {
                if (isValueX) {
                    long totalSeconds = new Double(value).longValue();
                    long currentSecond = totalSeconds % 60;

                    long totalMinutes = totalSeconds / 60;
                    long currentMinute = totalMinutes % 60;

                    long totalHour = totalMinutes / 60;
                    long currentHour = totalHour % 24;

                    if (currentMinute < 10 && currentSecond < 10) {
                        return String.format("%d:0%d:0%d", currentHour, currentMinute, currentSecond);
                    }
                    if (currentMinute < 10) {
                        return String.format("%d:0%d:%d", currentHour, currentMinute, currentSecond);
                    }
                    if (currentSecond < 10) {
                        return String.format("%d:%d:0%d", currentHour, currentMinute, currentSecond);
                    }
                    return String.format("%d:%d:%d", currentHour, currentMinute, currentSecond);


                } else {
                    return super.formatLabel(value, isValueX) + " dBm";
                }
            }
        });

And here is the method:

    private double getDateX() {

        long totalMilliSeconds = System.currentTimeMillis();

        long currentSecond = Long.parseLong((new SimpleDateFormat("s", Locale.US)).format(new Date(totalMilliSeconds)));


        long currentMinute = Long.parseLong((new SimpleDateFormat("m", Locale.US)).format(new Date(totalMilliSeconds)));


        long currentHour = Long.parseLong((new SimpleDateFormat("H", Locale.US)).format(new Date(totalMilliSeconds)));

        double myTime = currentSecond + currentMinute * 60 + currentHour * 60 * 60;

        return myTime;

    }

Enjoy the code!
Note: I'm sorry for my english.

**Comment by SteveLamont** [comment]
I've observed a similar issue when setting the Viewport min X and max X.  Because the Viewport's dimensions are declared as floats in the RectF, these values get truncated.  Then when the time values are fed back to DateAsXAxisLabelFormatter.formatLabel() they can produce the wrong result.

For example, if minX is set to 1454832000000 (Sun Feb 07 00:00:00 PST 2016), this gets truncated to 1454831960064, which is roughly 40 seconds earlier -- in other words, the previous day -- and the formatter return "Feb 6, 2016".

I suggest using an object with greater precision to store these values.

**Comment by jjoe64** [comment]
implementation side problem
