### ISSUE TITLE
GraphViewSeries and LineGraphView cannot be resolved.

### ISSUE THREAD

**Issue by AdroidQuest** [jjoe64/GraphView#345]
Hi, 

I have copied the jar flle into my libs folder but still getting error in the following line (cannot resolve GraphViewSeries). 

--- import com.jjoe64.graphview.GraphViewSeries;

I am also getting error for the following (cannot resolve LineGraphView)

---- import com.jjoe64.graphview.LineGraphView;

Some thoughts will be appreciated.

**Comment by Demian87** [comment]
+1 
Any piece of advice?

**Comment by Demian87** [comment]
Found this post: http://www.android-graphview.org/documentation/migration-from-31-to-40
Probably, I need to migrate the project =(
