### ISSUE TITLE
The line graph won't draw if Y value does not change

### ISSUE THREAD

**Issue by caesarleong** [jjoe64/GraphView#346]
I am try to draw a line graph  start with a horizontal line, so I call resetData() with feeding a DataPoint array which X are (1, 2, 3, 4, 5, 6,...) and Y are all 1. I suppose it will draw horizontal line but I didn't see it untill I append a DataPoint with a Y value change. Is that a bug? or if it is not a issue, would you please advise how can I draw a horizontal line? Thank you very much.

**Comment by ParasDPain** [comment]
`resetData()` removes all the data points in the series and `appendData()` adds a new `DataPoint` to the existing data, like the `List.Add()` method. I suggest you use `appendData()` only. If the issue persists, please post your code and snippets of the resultant graph.

**Comment by caesarleong** [comment]
Thanks for reply, I change the design so don't need this feature again. ^_^
