### ISSUE TITLE
Labels on the x-axis are not displayed

### ISSUE THREAD

**Issue by SonGoku85** [jjoe64/GraphView#348]
Hello

I can communicate in English not express so well, so I've hunted there through google translator:

I # 309 reprodizieren the entry without any problems.

Galaxy S4 I9505
Android 5.0.1

When the attribute "android: hardwareAccelerated" the manifest in the activity tag on "false" is, the labels on the x-axis are not displayed. If you remove the attribute or set it to "true", it works without any problems.

#####
Original in German:

Hallo

Ich kann mich in englisch leider nicht so gut ausdrücken, deher habe ich das hier durch den Google-übersetzer gejagt:

Ich kann den Eintrag #309 ohne Probleme reprodizieren.

Galaxy S4 I9505
Android 5.0.1

Wenn man im Manifest im activity-Tag das Attribut "android:hardwareAccelerated" auf "false" setzt, werden die Labels auf der X-Achse nicht angezeigt. Entfernt man das Attribut oder setzt es auf "true", funktioniert es wieder ohne Probleme.

**Comment by jjoe64** [comment]
super!! vielen dank für dein Feedback! Jetzt ist das Rätzel endlich gelößt :+1:

**Comment by aloiserz** [comment]
Hi ! I would like to know when you will add the "GraphView-4.0.2.jar".
Do you already have a solution for the "x-axis not displayed" ? 
Thanks in advance !

**Comment by SonGoku85** [comment]
Since the bug is expected to be fixed only in 4.0.2, but we are a definite no nich in 4.0.1!
Simply described as above "android: hardwareAccelerated" set to "true".

#########

Da der Bug vorraussichtlich erst in 4.0.2 behoben wird, wir aber nich bei 4.0.1 stehen ein klares Nein!

Einfach wie oben beschrieben "android:hardwareAccelerated" auf "true" setzen.

**Comment by SonGoku85** [comment]
Since the bug is expected to be fixed only in 4.0.2, but still we are a resounding no in 4.0.1!
Simply described as above "android: hardwareAccelerated" set to "true".


##########


Da der Bug voraussichtlich erst in 4.0.2 behoben wird, wir aber noch bei 4.0.1 stehen ein klares Nein!
Einfach wie oben beschrieben "android:hardwareAccelerated" auf "true" setzen.

**Comment by aloiserz** [comment]
Ok thank you, but I tried to add : android:hardwareAccelerated="true" and it doesn't work either.
I put it in a fragment, is it possible ? Here is a part of my fragment.xml : 
   <com.jjoe64.graphview.GraphView
        android:layout_width="match_parent"
        android:layout_height="fill_parent"
        android:layout_weight="1"
        android:id="@+id/graph"
        android:hardwareAccelerated="true" />

**Comment by SonGoku85** [comment]
No. That comes into manifest in the activity tag.

<activity
  android:name=".Graph"
  android:label="@string/menue_graph"
  android:stateNotNeeded="true"
  android:hardwareAccelerated="true"
  android:screenOrientation="portrait">
</activity>

Or just leave completely out if it is in there.

If that does not help, there is a second reason, which I do not know.

##################


Nein. Das kommt ins Manifest in den activity-Tag.

<activity
  android:name=".Graph"
  android:label="@string/menue_graph"
  android:stateNotNeeded="true"
  android:hardwareAccelerated="true"
  android:screenOrientation="portrait">
</activity>

Oder eben ganz raus lassen, wenn es drin steht.

Wenn das nicht hilft, gibt es noch eine zweite Ursache, die ich nicht kenne.

**Comment by aloiserz** [comment]
Thank you very much it works !

**Comment by jjoe64** [comment]
TODO:

- add in Documentation
- check for flag on runtime and throw exception
