### ISSUE TITLE
Points re-plot after scroll

### ISSUE THREAD

**Issue by DrBeak1** [jjoe64/GraphView#349]
Say I have 20 points (1-10 & 71-80). If I set the max allowed on screen at any given time to 10 and graph my values everything looks great. Then when I scroll to the right to see the remaining points after I stop scrolling the plots adjust themselves so that they are relative to the values that are visible on the screen instead of having one long continuous line graph. Is there anyway to prevent this re-plot after scrolling?

Thanks for any help.

**Comment by jjoe64** [comment]
fixed
