### ISSUE TITLE
Null Pointer exception

### ISSUE THREAD

**Issue by shubhamshuklaer** [jjoe64/GraphView#352]
I am getting a null pointer exception on line no 183

    if (prevValue.getX() >= from) {
inside function
    public Iterator<E> getValues(final double from, final double until) {
 in BaseSeries.java. The value of prevValue is null.
 
This is what is happening. I have 3 Line Graph series in  a graph and I am updating them at different time. When the onDraw function of  GraphView.java is called on line 298 you are calling draw function for each series. In the draw function of LineGraphSeries.java on line no 158-159 you are getting the viewport size by 

    double maxX = graphView.getViewport().getMaxX(false);
    double minX = graphView.getViewport().getMinX(false);
 and then on line 171 

    Iterator<E> values = getValues(minX, maxX);
you are calling the getValues function from BaseSeries.java. Now Since I am updating the series at different time so before the onDraw function of GraphView.java is called some of my series have data and some don't but each time I update a Series I update the Graph's viewport MinX and MaxX value to show relevant data so one possible calling of getValues(in BaseSeries.java) can have parameters from=3000 and until=3050 while the Series is empty.  The first condition 

    if (from <= getLowestValueX() && until >= getHighestValueX()) { 
fails cause (from<=0 && unti>=0) gives false. Hence it goes to else part. Then on line 183 there is no check if prevValue is null before calling a function on it. The value of prevValue will be null if the Series is empty.

**Comment by jjoe64** [comment]
fixed
