### ISSUE TITLE
NullPointException had been throw

### ISSUE THREAD

**Issue by ljsalm089** [jjoe64/GraphView#354]
I got a NullPointException in class BaseSeries.
the code in method getValues(double, double):
if(prevue.getX() >= form)
and 
return nextValue != null && (nextValue.getX() <= until || plusOne);

when mData is null of isEmpty, it will throw NullPointException.
I am sorry I can't offer the error log cause I had fixed the code in my computer and I had changed other code so I can't push the to this repository.

**Comment by jjoe64** [comment]
fixed
