### ISSUE TITLE
Icons along and just on top of graph

### ISSUE THREAD

**Issue by gurappa** [jjoe64/GraphView#355]
Hi,  I need help to understand if the library supports showing icons along the graph and just on top of it. I want to display an icon as well depending on the value on X axis. Can I do that with this library?

**Comment by ParasDPain** [comment]
Do you mean like an overlay on the graph? I'm not too familiar with the library so I would suggest that you can always add a new `ImageView` and control it's position on the `canvas` using the `GetX(true)` method of the `Series` data. The canvas might have to be a new `View` altogether. I don't think you can add objects directly on the Canvas used by the Graph.

**Comment by jjoe64** [comment]
with the Point Series you can draw what ever you want on the specific points in the graph
