### ISSUE TITLE
Serries draw background, negative values

### ISSUE THREAD

**Issue by TEH3OP** [jjoe64/GraphView#361]
Hi.
When i use:
                series.setBackgroundColor(Color.YELLOW);
                series.setDrawBackground(true);
If the value Y is positive, then it works fine.
But if the value Y is negative, background is drawn to the bottom of the chart, although it should be drawn to the zero axis.
Fix it please.

**Comment by jjoe64** [comment]
related to #422 and #433

**Comment by jjoe64** [comment]
wont be implemented in this version. it's already complex and draw background has not good performance anyway
