### ISSUE TITLE
LineGraphSeries with single DataPoint won't display

### ISSUE THREAD

**Issue by sruitasuk** [jjoe64/GraphView#364]
in LineGraphSeries
if we have only 1 DataPoint

it won't display anything in the graph even if we setDrawDataPoints to TRUE

I notices that in 4.0.1 
in LineGraphSeries.java at line 281

    if (i > 0) {
        // .....
    } else if (mStyles.drawDataPoints) {
        //fix: last value not drawn as datapoint. Draw first point here, and then on every step the end values (above)
        float first_X = (float) x + (graphLeft + 1);
        float first_Y = (float) (graphTop - y) + graphHeight;
        /**** this line might be the mistake,, it has comment at the start of it ****/
        //TODO canvas.drawCircle(first_X, first_Y, dataPointsRadius, mPaint);
    }

Thanks,

**Comment by jjoe64** [comment]
should render the datapoint
