### ISSUE TITLE
x- axis time resolution

### ISSUE THREAD

**Issue by davix10** [jjoe64/GraphView#368]
Dear jjoe64,
I want to use your library in order to plot some data and their relative time. My time resolution is the second, hence I need a time axis with the resolution of the second.
Looking at your documentation I found this example:

// generate Dates
Calendar calendar = Calendar.getInstance();
Date d1 = calendar.getTime();
calendar.add(Calendar.DATE, 1);
Date d2 = calendar.getTime();
calendar.add(Calendar.DATE, 1);
Date d3 = calendar.getTime();

When I tried this on my app, I found that if I add 1 day it works fine, but if I add a second it does not work. I tried also adding one minute and it keeps on working fine, but if I add a second it does not create the chart.

Is there something wrong in my way of using it?
Is it possible to have a resolution of one second?

Thanks

Davix10

**Comment by jgrocha** [comment]
Same problem here. I' showing a graph with temperatures measured on Arduino at shorts intervals.

```
series.appendData(new DataPoint(new Date(temp.getMillis()), temp.getValue()), true, 40);
```

I can add new points to the graph every second or so, but to create the initial graph, the best I can is to create the points with 30 seconds difference.

```
        Calendar calendar = Calendar.getInstance();
        calendar.add(Calendar.SECOND, -30);
        Date d3 = calendar.getTime();
        calendar.add(Calendar.SECOND, -30);
        Date d2 = calendar.getTime();
        calendar.add(Calendar.SECOND, -30);
        Date d1 = calendar.getTime();
```

I would like to create the initial graph with just a few seconds between the initial points.

But I still working on this. I'll try to find out the solution.

**Comment by jjoe64** [comment]
use the manual viewport. in version 4.1 there is also the option to disable the humanRounding feature which could make trouble here
