### ISSUE TITLE
How to display XYPlot based on timeseries 

### ISSUE THREAD

**Issue by forum6691** [jjoe64/GraphView#369]
Hello everybody.
I wish to display a XYPLOT to display the speed of a vehicule. Y data are the speed in km/h. Xdata are the time in millseconds and represents the hour/minute/seconds of the measure. The interval between X measures are variable because the acquistion system of the speed is not realtime. Example: the first measure is at 0 ms, the second at 10 ms, the third at 15 ms, the fourth at 23 ms, the fifth at 34 ms, and again...

So which graph can I use in Graphview to display these type of measures ?
I don't find in the documentation this capability. It seems that Xdata are just an integer value to reference the position in the list of values and can not be a numeric value to have a variable scale along the Xaxis !

Thanks for help.

**Comment by jjoe64** [comment]
thats the default LineGraph. see the documentation and examples please
