### ISSUE TITLE
How to show on a line graph one data from a list per second ?

### ISSUE THREAD

**Issue by aloiserz** [jjoe64/GraphView#370]
Hello, I am trying to show data on a line graph. Data are in a list where data arrive every second. So I want to add one data per seconde on my graph. It didn't work because once my fragment opened I don't succeed in having new datas which arrive in my activity. Could you help me ? Thanks in advance !

mSeries1 = new LineGraphSeries<DataPoint>();
graph1.addSeries(mSeries1); 
mSeries1.setColor(Color.RED);
	     				                                			        
if (list6.isEmpty() == false){
  Iterator<String> iterator = list6.iterator();
  while(iterator.hasNext()) {
    data = iterator.next();
	     				                                			        		if(data.contains("DLCLoad6")){
final String data6= data.replaceAll("DLCLoad6, (\\S+)", "$1");
 mTimer1 = new Runnable() {
 @Override
public void run() {
try{
datad = Double.parseDouble(data6);
	     				                                				            			}catch(NumberFormatException e){
	     				                                				            				
 } 
graph2LastXValue += 1d;
try{
mSeries1.appendData(new DataPoint(graph2LastXValue, datad), true, 60);
mHandler.postDelayed(this, 1000);
}catch(NullPointerException e){
	     				                                						                }catch(Exception e){ 
	     				                                						                 	
 }
 }
};
mHandler.postDelayed(mTimer1, 1000);
}
}
}

**Comment by jjoe64** [comment]
no issue of graphview
