### ISSUE TITLE
GraphView shows wrong graph in real time mode when scrollToEnd is true

### ISSUE THREAD

**Issue by Assafkalfa** [jjoe64/GraphView#372]
First of all, Thank you to your graph library !

I tried to build sample app that shows Acceleroemter Graph, using Graph View 4.0.1 and I have an issue because the graph is wrong and the axis are not update.
I already asked the question in stackoverflow: http://stackoverflow.com/questions/33215733/graphview-shows-wrong-graph-in-real-time-mode-when-scrolltoend-is-true

I'll be glad you if you can help me with this
Thank you!

**Comment by jjoe64** [comment]
seems to be closed
