### ISSUE TITLE
Decimal Numbers

### ISSUE THREAD

**Issue by buutqn** [jjoe64/GraphView#377]
I am new in that development stuff, and i found this amazing library that im using, but, i have this little problem, i am using only integer variables and the graphic insists to put decimal numbers on the labels both y and x, is there any method or way that makes it doesnt happen?

thanks.

**Comment by ptrasatti** [comment]
Buutdn,

     With Graphview you can format your axis labels with a custom LabelFormater. With your own routine you can create a string that doesn't have the decimal points in the numbers. It's very easy and works great. Graphview will pass you the x and y values one at a time and you return the string you want to display at that point on the x or y axis.

Here's the documentation which includes  an example:

http://www.android-graphview.org/documentation/label-formatter

Good luck,

Phil

**Comment by jjoe64** [comment]
thanks @ptrasatti :+1:
