### ISSUE TITLE
GraphView slow down app performance by the time.  

### ISSUE THREAD

**Issue by AhmedMostfa** [jjoe64/GraphView#378]
Hello
. I have tried multiple codes to draw a graph for the data ( "Byte[] readBuffer") that is coming from Bluetooth module connected with pressure sensor. The graph should show my digital values that start from 0000 to 1024 without problems. 
But what happens is that by the time running, I'm getting unexpected delay in the graph updating. 
I don't have any sampling issues (once i receive the data from my sensor that is connecting with the Bluetooth module, i should have a very smooth graph like waterfall). I'm pretty sure that I'm missing some line of codes that should be implemented.   I guess the problem is within Runnable() class that runs on UI with respect to  case: MESSAGE_READ.
here is my code in MainActivity. 

package com.ahmed.bluetooth;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.text.SimpleDateFormat;

import android.annotation.SuppressLint;
import android.content.res.Configuration;
import android.app.AlertDialog;
import android.content.Context;
import android.content.DialogInterface;
import android.content.SharedPreferences;
import android.media.MediaPlayer;
import android.media.RingtoneManager;
import android.net.Uri;
import android.support.v7.app.ActionBarActivity;
import android.app.Activity;
import android.bluetooth.BluetoothAdapter;
import android.bluetooth.BluetoothDevice;
import android.content.Intent;
import android.graphics.Color;
import android.os.Bundle;
import android.os.Handler;
import android.os.Message;
import android.util.Log;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.CompoundButton;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.Toast;
import android.widget.ToggleButton;

import com.jjoe64.graphview.GraphView;
import com.jjoe64.graphview.series.DataPoint;
import com.jjoe64.graphview.series.LineGraphSeries;

@SuppressWarnings("UnusedAssignment")
public class MainActivity extends ActionBarActivity {

    private void postData(final double time, final int pressure) {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                mCurrentLineGraph.appendData(new DataPoint(time, pressure), true, 1000);
            }
        });
    }

    private static final String TAG = "BluetoothChat";

    //toggle button for sound
    private ToggleButton toggleButton;

    String lastInput;
    //String[] digitArray = {"", "", "", "", "", "", "", "", "", ""};
    // String[] poundArray = {"", "", "", "", "", "", "", "", "", ""};
    // int len_digitalArray = 0;
    // int i = 0;//for loop

    //float xm = 0;//to find the mean for x array
    //float ym = 0;//to find the mean for y array.
    //float b0 = 0; //to find b0 of linear regression.
    //float b1 = 0;//to find b1 of linear regression.
    //float nn = 0;//find numerator of linear equation.
    //float dd = 0;//find denominator of linear equation.
    // Message types sent from the BluetoothChatService Handler
    public static final int MESSAGE_STATE_CHANGE = 1;
    public static final int MESSAGE_READ = 2;
    public static final int MESSAGE_WRITE = 3;
    public static final int MESSAGE_DEVICE_NAME = 4;
    public static final int MESSAGE_TOAST = 5;
    public static final int MESSAGE_ALERTDIALOG = 6;

    // Key names received from the BluetoothChatService Handler
    public static final String DEVICE_NAME = "device_name";
    public static final String TOAST = "toast";
    // Intent request codes
    private static final int REQUEST_CONNECT_DEVICE = 2;
    private static final int REQUEST_ENABLE_BT = 3;
    // private static final int samplePeriod = 24 * 60 * 60; //24hrs x 60 mains x 60 secs    x 10 (of 100ms)

    private LinearLayout chartContainer;
    private int pressure;

    //Properties for GraphView
    private GraphView mGraphView;
    private LineGraphSeries<DataPoint> mCurrentLineGraph = null;
    private ArrayAdapter<String> mDigitalInAdapter;
    private ArrayAdapter<String> mPoundAdapter;
    private ArrayAdapter<String> mRecordingAdapter;
    private int mSelectedPoundIndex;

    // Layout Views
    // Name of the connected device
    private String mConnectedDeviceName = null;
    //  public String[] d;
    // Local Bluetooth adapter
    private BluetoothAdapter mBluetoothAdapter = null;
    // Member object for the chat services
    private BluetoothChatService mChatService = null;

    //Alert
    private MediaPlayer mMPlayer;
    private ToggleButton mAlertButton;
    private ToggleButton dataRecordButton;
    private boolean mMPlayerReady = false;
    private double time = 0.0;

    @SuppressLint("HandlerLeak")
    public MainActivity() {
        mHandler = new Handler() { // this the handler
            //private double time = 0.0;

            @Override
            public void handleMessage(Message msg) {
                byte[] readBuf;
                switch (msg.what) {
                    case MESSAGE_STATE_CHANGE:
                        Log.i(TAG, "MESSAGE_STATE_CHANGE: " + msg.arg1);
                        switch (msg.arg1) {
                            case BluetoothChatService.STATE_CONNECTED:
                                Log.i(TAG, "STATE_CONNECTED: " + msg.arg1);
                                setStatus(getString(R.string.title_connected_to,
                                        mConnectedDeviceName));
                                mDigitalInAdapter.clear();
                                startGraph();
                                break;
                            case BluetoothChatService.STATE_CONNECTING:
                                Log.i(TAG, "STATE_CONNECTING: " + msg.arg1);
                                setStatus(R.string.title_connecting);
                                break;
                            case BluetoothChatService.STATE_LISTEN:
                            case BluetoothChatService.STATE_NONE:
                                Log.i(TAG, "STATE_LISTEN | STATE_NONE: " + msg.arg1);
                                setStatus(R.string.title_not_connected);
                                break;
                        }
                        break;
                    case MESSAGE_WRITE:
                        Log.i(TAG, "MESSAGE_WRITE: " + msg.arg1);
                        byte[] writeBuf = (byte[]) msg.obj;
                        // construct a string from the buffer
                        String writeMessage = new String(writeBuf);
                        mDigitalInAdapter.add("Me:  " + writeMessage);
                        break;
                    case MESSAGE_READ://here I'm reading...
                        Log.i(TAG, "MESSAGE_READ: " + msg.arg1);
                         readBuf = (byte[]) msg.obj; // Array that will back the new buffer.
                        // construct a string from the valid bytes in the buffer
                        String readMessage = new String(readBuf, 0, msg.arg1);

                        ByteBuffer buffer = ByteBuffer.wrap(readBuf, 0, readBuf.length);
                        buffer.order(ByteOrder.BIG_ENDIAN);
                        Log.i(TAG, "digital read in: " + readMessage + ", str-" + pressure + " s-");

                        String[] strNumbers = readMessage.split("\r"); //stand for ASCII(13);
                        if (strNumbers.length > 0) {
                            Log.i(TAG, "readMessage = " + readMessage);
                            //  if (strNumbers.length > 0) {
                            //  Log.i(TAG, "digital after split: " + strNumbers[0] + ", length=" + strNumbers.length);
                            // } else {
                            //     Log.i(TAG, "no data read!");
                            //  }

                            readMessage = strNumbers[0];
                            lastInput = strNumbers[0];
                            try {
                                pressure = Integer.valueOf(readMessage);
                            } catch (NumberFormatException e) {
                                Log.e(TAG, "NumberFormatException - " + e.getMessage());
                                e.printStackTrace();
                            }

                            if (pressure >= 0) {
                                pushDataIntonAdapter("mDigitalInAdapter",mDigitalInAdapter,pressure);

                                float pound;// = 0x0f;
                                try {
                                    pound = digitalToPoundConvert(pressure);
                                    Log.i(TAG, String.format("Digital to Pound convert: %04d -> %4.2f", pressure, pound));
                                    pushDataIntonAdapter("mPoundAdapter",mPoundAdapter,pound);
                                    if (mPoundAdapter != null) {
                                        // check if new pounds >= last recorded
                                        if (mRecordingAdapter.getCount() > 0) {
                                            float last_pounds;//= 0.0f;
                                            float current_pounds;// = 0.0f;
                                            last_pounds = Float.parseFloat(mRecordingAdapter.getItem(mRecordingAdapter.getCount() - 1));
                                            current_pounds = Float.parseFloat(mPoundAdapter.getItem(mPoundAdapter.getCount() - 1));

                                            if (current_pounds >= last_pounds) {
                                                // turn data record back on
                                                sendEmptyMessage(MESSAGE_ALERTDIALOG);
                                            }
                                        }

                                     }
                                    if (mCurrentLineGraph != null) {

                                        postData(time, pressure);
                                        time++;
                                         //onResume();
                                       // mCurrentLineGraph.appendData(new DataPoint(time, pressure), false, 1000);
                                        //noinspection NumericOverflow
                                       //time = time + 1.0 /20.0;

                                    }
                                } catch (Exception e) {
                                    Log.e(TAG, "onProgressUpdate failed: " + e.getMessage());
                                }

                            } else {
                                Log.i(TAG, "The digital was - " + 0);
                            }
                        }
                        break;
                    case MESSAGE_DEVICE_NAME:
                        Log.i(TAG, "MESSAGE_DEVICE_NAME: " + msg.arg1);
                        // save the connected device's name
                        mConnectedDeviceName = msg.getData().getString(DEVICE_NAME);
                        Toast.makeText(getApplicationContext(),
                                "Connected to " + mConnectedDeviceName,
                                Toast.LENGTH_SHORT).show();
                        break;
                    case MESSAGE_TOAST:
                        Log.i(TAG, "MESSAGE_TOAST: " + msg.arg1);
                        Toast.makeText(getApplicationContext(),
                                msg.getData().getString(TOAST), Toast.LENGTH_SHORT)
                                .show();
                        break;
                    case MESSAGE_ALERTDIALOG:
                        Log.i(TAG,"MESSAGE_ALERTDIALOG"+ msg.arg1);
                        AlerThreshold();

                        break;
                }
            }
        };
    }

    private void AlerThreshold() {

    }

    private void pushDataIntonAdapter(String name, ArrayAdapter<String> adapter, float pressure) {
        if (adapter != null) {

            adapter.add(String.format("%04.2f", pressure));
            adapter.notifyDataSetChanged();
            Log.i(TAG, "added -  " + pressure);
        }
    }
    //public View.OnClickListener OnKeyListener;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        //get icon action bar

        getSupportActionBar().setDisplayShowHomeEnabled(true);
        getSupportActionBar().setLogo(R.mipmap.ic_launcher);
        getSupportActionBar().setDisplayUseLogoEnabled(true);
        setContentView(R.layout.activity_main);

        Log.i(TAG, "+++ ON CREATE +++");
        chartContainer = (LinearLayout) findViewById(R.id.line_graph);
        mRecordingAdapter = new ArrayAdapter<>(this, R.layout.message);

        // calibrateButton = (Button) findViewById(R.id.Calibrate);
        //calibrateButton.setOnClickListener(calibrateListener);

        //Rest Calibrate and calling function.
//        Button resetButton = (Button) findViewById(R.id.Reset);
        //  resetButton.setOnClickListener(resetButtonListener);
        //Define start Start finding bo $ b1
        //startButton = (Button) findViewById(R.id.Start);
        //startButton.setEnabled(false);
        //startButton.setOnClickListener(startButtonListener);

        ListView recordingListView = (ListView) findViewById(R.id.ls_record_list);
        if (recordingListView != null) {
            recordingListView.setAdapter(mRecordingAdapter);  //Sets the data behind this ListView.
        }
        mAlertButton = (ToggleButton) findViewById(R.id.toggleButton);
        // Get local Bluetooth adapter
        mBluetoothAdapter = BluetoothAdapter.getDefaultAdapter();
        // If the adapter is null, then Bluetooth is not supported
        if (mBluetoothAdapter == null) {
            Toast.makeText(this, "Bluetooth is not available",
                    Toast.LENGTH_LONG).show();
            finish();
        }

        //Users guidance.
        My_alert my_alert = new My_alert();
        my_alert.show(getFragmentManager(), "My alert");

        //hide and pop up editText code.
        // init();
    }//end OnCreate().

    /*
        void init() {
            inputEdit = (EditText) findViewById(R.id.inputEditView);
            inputEdit.setOnClickListener(OnKeyListener);
            inputEdit.setOnKeyListener(new View.OnKeyListener() {
                @Override
                public boolean onKey(View v, int keyCode, KeyEvent event) {
                    if ((event.getAction() == KeyEvent.ACTION_DOWN) && (keyCode == KeyEvent.KEYCODE_ENTER)) {
                        //Toast.makeText(MainActivity.this,inputEdit.getText(),Toast.LENGTH_SHORT).show();
                        hideKeyboard();
                        return true;
                    }
                    return false;
                }
            });
        }

        void hideKeyboard() {
            //InputMethodManager inputMag = (InputMethodManager) getSystemService(Context.INPUT_METHOD_SERVICE);
            inputMag.toggleSoftInput(0, 0);
        }//end keyboard configuration for edit Text.
    */
    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        if (newConfig.orientation == Configuration.ORIENTATION_PORTRAIT) {
            Toast.makeText(MainActivity.this, "Portrait mode", Toast.LENGTH_SHORT).show();
        } else if (newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE) {
            Toast.makeText(MainActivity.this, "Portrait mode", Toast.LENGTH_SHORT).show();

        }
    }

    /*

    //class for resting the calibration.
    public View.OnClickListener resetButtonListener = new View.OnClickListener() {

        @Override
        public void onClick(View v) {

            AlertDialog alertDialog_1 = new AlertDialog.Builder(MainActivity.this).create();
            alertDialog_1.setMessage("You will reset your sensors calibration. You would have to go through calibrating the sensor again.\n" +
                    "To calibrate the sensors, please follow up the instructions. ");
            alertDialog_1.setTitle("Reset!!");
            alertDialog_1.setIcon(R.drawable.icon);
            alertDialog_1.setButton("Ok", new DialogInterface.OnClickListener() {
                public void onClick(DialogInterface dialog, int which) {
                    //turn off the alert at "Ok" click.
                    //dataRecordButton.setChecked(false);
                    b0 = 0;
                    b1 = 0;
                    i = 0;
                    len_digitalArrary = 0;
                    startButton.setEnabled(false);
                    calibrateButton.setEnabled(true);
                }
            });
            alertDialog_1.show();

          //  b0 = 0;
           // b1 = 0;
          //  i = 0;
         //   len_digitalArrary = 0;
         //   startButton.setEnabled(false);
         //   calibrateButton.setEnabled(true);
        }

    };
    */

    /*
    //Linear regression function that finds bo & b1
    public View.OnClickListener startButtonListener = new View.OnClickListener() {

        @Override
        public void onClick(View v) {
            for (int i = 0; i < len_digitalArrary; i++) {
                xm += Float.parseFloat(digitArray[i]);
                ym += Float.parseFloat(poundArray[i]);
            }
            xm = xm / (len_digitalArrary + 1);
            ym = ym / (len_digitalArrary + 1);
            for (int i = 0; i < len_digitalArrary; i++) {

                nn += (Float.parseFloat(digitArray[i]) - xm) * (Float.parseFloat(poundArray[i]) - ym);//it is just the equation of how to find bo
                dd += (Float.parseFloat(digitArray[i]) - xm) * (Float.parseFloat(digitArray[i]) - xm);//equation of how to find b1

            }
            b1 = nn / dd;
            b0 = ym - b1 * xm;
            Toast.makeText(v.getContext(), "Independent: " + b0 + " --- " + "Dependent: " + b1, Toast.LENGTH_SHORT).show();
            //startButton.setEnabled(false);
            Toast.makeText(v.getContext(), "Press (Data Record) once you feel the pain at the painful pound.", Toast.LENGTH_LONG).show();
            //set data record to true.
            btn.setEnabled(true);

        }
    };
    */
 /*
    //to enter both pounds and digits at same time.
    public View.OnClickListener calibrateListener = new View.OnClickListener() {

        @Override
        public void onClick(View v) {

            if (len_digitalArrary < 10) {
                digitArray[len_digitalArrary] = lastInput;
                poundArray[len_digitalArrary] = inputEdit.getText().toString();
                Toast.makeText(v.getContext(), "Digit: " + digitArray[len_digitalArrary] + " --- " + "Pound: " + poundArray[len_digitalArrary], Toast.LENGTH_SHORT).show();
                // i=i+1;
                Toast.makeText(v.getContext(), "You entered: " + (len_digitalArrary + 1) + " weights .Please keep adding weights to calibrate the sensor", Toast.LENGTH_SHORT).show();
                len_digitalArrary++;
                if (len_digitalArrary > 4) startButton.setEnabled(true);

            } else {
                //startButton.setEnabled(true);
                Toast.makeText(v.getContext(), "You have reached: " + (len_digitalArrary + 1) + ". Please Click start button", Toast.LENGTH_LONG).show();
                calibrateButton.setEnabled(false);
            }

        }
    };
    */
    @Override
    public void onStart() {
        super.onStart();
        Log.i(TAG, "++ ON START ++");

        // If BT is not on, request that it be enabled.
        // setupChat() will then be called during onActivityResult
        if (!mBluetoothAdapter.isEnabled()) {
            Intent enableIntent = new Intent(BluetoothAdapter.ACTION_REQUEST_ENABLE);// Show a system activity that allows the user to turn on Bluetooth.
            startActivityForResult(enableIntent, REQUEST_ENABLE_BT);
            // Otherwise, setup the chat session
        } else {
            if (mChatService == null) {
                setupChat();
                GraphSetup();
                Button btn = (Button) findViewById(R.id.btn_record_data);
                if (btn != null) {
                    btn.setOnClickListener(mOnClickListener);
                }
                btn = (Button) findViewById(R.id.btn_clear_record);
                if (btn != null) {
                    btn.setOnClickListener(mOnClickListener);
                }
            }
        }
        if (mMPlayer == null) {
            Uri notification = RingtoneManager.getDefaultUri(RingtoneManager.TYPE_ALL);
            Log.i(TAG, "Alert tone: " + notification.getPath());
            try {
                mMPlayer = new MediaPlayer();
                mMPlayer.setLooping(true); // MediaPlayer object shall remain in the Started state.
                mMPlayer.setDataSource(this, notification);
                mMPlayer.setOnPreparedListener(new MediaPlayer.OnPreparedListener() {
                    @Override
                    //transfers a MediaPlayer object in the Idle state to the Initialized state.
                    public void onPrepared(MediaPlayer mp) {// Preparing state is a transient state
                        //transfers the object to the Prepared state
                        mMPlayerReady = true;
                    }
                });
                mMPlayer.prepareAsync();  //An IllegalStateException is thrown if prepare() or prepareAsync() is called in any other state.

            } catch (IOException e) {
                Log.w(TAG, "onStart - IOException: " + e.getMessage());
            } catch (IllegalStateException e) {
                Log.w(TAG, "onStart - IllegalStateException: " + e.getMessage());
            }
        }
    }

    @Override
    public synchronized void onResume() {
        super.onResume();
        Log.i(TAG, "+ ON RESUME +");
//        Runnable mTimer1;
//        mTimer1 = new Runnable() {
//            @Override
//            public void run() {
//                mCurrentLineGraph.appendData(new DataPoint(time, pressure), true, 1000);
//                //mHandler.postDelayed(this,10);
//                time =time+0.005;
//            }
//        };
//        mHandler.postDelayed(mTimer1, (long) 0.005);
        //me
        // Performing this check in onResume() covers the case in which BT was
        // not enabled during onStart(), so we were paused to enable it...
        // onResume() will be called when ACTION_REQUEST_ENABLE activity
        // returns.
        if (mChatService != null) {
            // Only if the state is STATE_NONE, do we know that we haven't
            // started already
            if (mChatService.getState() == BluetoothChatService.STATE_NONE) {    //Get the current state of the local Bluetooth adapter.

                // Possible return values are STATE_OFF, STATE_TURNING_ON, STATE_ON, STATE_TURNING_OFF.
                // Start the Bluetooth chat services
                mChatService.start();
            }
        }
        if (mAlertButton != null) {
            mAlertButton.setOnCheckedChangeListener(mOnCheckedChangeListener);
        }
    }

    @Override
    public synchronized void onPause() {
        super.onPause();
        Log.e(TAG, "- ON PAUSE -");
        onResume();
    }

    @Override
    public void onStop() {
        super.onStop();
        Log.i(TAG, "-- ON STOP --");
        if (mMPlayer != null) {
            try {
                mMPlayer.stop();
            } catch (IllegalStateException e) {
                Log.w(TAG, "IllegalStateException on alert: " + e.getMessage());
            } finally {
                mMPlayer.release();
                mMPlayer = null;
                mMPlayerReady = false;

            }

        }
        super.onStop();
    }

    /**
     * Handling select item on Pound list view.
     */
    private final AdapterView.OnItemSelectedListener mOnItemSelectedListener = new AdapterView.OnItemSelectedListener() {
        @Override
        public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
            Log.i(TAG, "onItemSelected: " + position + " class: " + view.getClass().getSimpleName());
            mSelectedPoundIndex = position;
            Toast.makeText(view.getContext(), "You have just selected item: " + mPoundAdapter.getItem(position) + " from Pounds list", Toast.LENGTH_LONG).show();
        }
        @Override
        public void onNothingSelected(AdapterView<?> parent) {
            Toast.makeText(parent.getContext(), "You should select 1 item from the Pounds list.", Toast.LENGTH_LONG).show();
        }
    };
    /**
     * Handling touch event on Record Data and Clear button
     */
    protected final View.OnClickListener mOnClickListener = new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            int id = v.getId();
            switch (id) {
                case R.id.btn_record_data:
                    if (mPoundAdapter.getCount() == 0) {   // grtCount: How many items are in the data set represented by this Adapter.
                        break;
                    }
                    mSelectedPoundIndex = mPoundAdapter.getCount() - 1;
                    Log.i(TAG, "On adding record item [" + mSelectedPoundIndex + "," + mPoundAdapter.getCount() + "," + mPoundAdapter.getItem(mSelectedPoundIndex) + "]");
                    if (mSelectedPoundIndex >= 0 && mSelectedPoundIndex < mPoundAdapter.getCount()) {        // SharedPreferences = Interface for accessing and modifying preference data
                        SharedPreferences sp = getSharedPreferences(getPackageName(), Context.MODE_PRIVATE);
                        String selectedPound = mPoundAdapter.getItem(mSelectedPoundIndex);
                        if (mRecordingAdapter != null && mRecordingAdapter.getCount() < sp.getInt("recording", 5)) {     //getInt =Retrieve an int value from the preferences.
                            mRecordingAdapter.add(selectedPound);
                            Log.i(TAG, "Added 1 new record:" + selectedPound);
                            mRecordingAdapter.notifyDataSetChanged();

                        }

                    } else {
                        Toast.makeText(v.getContext(), "You should first select 1 item from the Pounds list.", Toast.LENGTH_LONG).show();
                    }
                    break;
                case R.id.btn_clear_record:
                    if (mRecordingAdapter != null && mRecordingAdapter.getCount() > 0) {
                        mRecordingAdapter.clear();
                        mRecordingAdapter.notifyDataSetChanged();
                    }
                default:
                    break;

            }

        }
    };

    private final ToggleButton.OnCheckedChangeListener mOnCheckedChangeListener = new CompoundButton.OnCheckedChangeListener() {
        @Override
        public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
            Log.i(TAG, "onCheckedChanged is " + isChecked);
            turnSound(isChecked);
        }
    };

    @Override
    public void onDestroy() {
        super.onDestroy();
        // Stop the Bluetooth chat services
        if (mChatService != null)
            mChatService.stop();
        Log.i(TAG, "--- ON DESTROY ---");
    }

    // The Handler that gets information back from the BluetoothChatService
    @SuppressLint("HandlerLeak")
    private final Handler mHandler;

    /**
     * Set action bar title by resource id
     *
     * @param resId - resource identifier.
     */
    private void setStatus(int resId) {
        if (getSupportActionBar() != null) {
            getSupportActionBar().setSubtitle(resId);
        }
    }

    /**
     * Set action bar title by
     *
     * @param subTitle - the title in string.
     */
    private void setStatus(CharSequence subTitle) {
        if (getSupportActionBar() != null) {
            getSupportActionBar().setSubtitle(subTitle);
        }

    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        Log.i(TAG, "onActivityResult " + resultCode);
        switch (requestCode) {
            case REQUEST_CONNECT_DEVICE:
                Log.i(TAG, "..from REQUEST_CONNECT_DEVICE: " + resultCode);
                // When DeviceListActivity returns with a device to connect
                if (resultCode == Activity.RESULT_OK) {
                    connectDevice(data);
                }
                break;
            case REQUEST_ENABLE_BT:
                Log.i(TAG, "..from REQUEST_ENABLE_BT: " + resultCode);
                // When the request to enable   returns
                if (resultCode == Activity.RESULT_OK) {
                    // Bluetooth is now enabled, so set up a chat session
                    setupChat();
                    //setup graph
                    GraphSetup();

                } else {
                    // User did not enable Bluetooth or an error occurred
                    Log.d(TAG, "BT not enabled");
                    Toast.makeText(this, R.string.bt_not_enabled_leaving,
                            Toast.LENGTH_SHORT).show();
                    finish();
                }
                break;
            default:
                break;
        }
    }

    /**
     * Start the connection with device.
     *
     * @param data - intent data which included device's mac address.
     */
    private void connectDevice(Intent data) {
        // Get the device MAC address
        String address = data.getExtras().getString(                 //get.Extras:- Retrieves a map of extended data from the intent.
                DeviceListActivity.EXTRA_DEVICE_ADDRESS);
        // Get the BluetoothDevice object
        BluetoothDevice device = mBluetoothAdapter.getRemoteDevice(address);
        // Attempt to connect to the device
        mChatService.connect(device);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater inflater = getMenuInflater();
        inflater.inflate(R.menu.option_menu, menu);
        return true;

    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        Intent intentActivity;
        switch (item.getItemId()) {
            case R.id.connect_scan:
                // Launch the DeviceListActivity to see devices and do scan
                intentActivity = new Intent(this, DeviceListActivity.class);
                startActivityForResult(intentActivity, REQUEST_CONNECT_DEVICE);
                return true;
            case R.id.clean_graph:
                GraphClear();
                return true;
            case R.id.action_share:
                Intent shareIntent = new Intent(Intent.ACTION_SEND);
                shareIntent.setType("text/plain");
                shareIntent.putExtra(Intent.EXTRA_TEXT, "text to share");
                startActivity(shareIntent);
                return true;
            case R.id.review_guidance:
                //Users guidance.
                My_alert my_alert = new My_alert();
                my_alert.show(getFragmentManager(), "My alert");
                return true;
            case R.id.navigate:
                startActivity(new Intent(this, SubActivity.class));
            default:
                break;

        }

        return false;
    }

    /**
     * Setup GraphView
     */
    private void setupChat() {
        Log.d(TAG, "setupChat()");

        // Initialize the array adapter for the conversation thread
        mDigitalInAdapter = new ArrayAdapter<>(this,
                R.layout.message);
        mPoundAdapter = new ArrayAdapter<>(this,
                R.layout.message);
        ListView listView = (ListView) findViewById(R.id.ls_digital_in);
        if (listView != null) {
            listView.setAdapter(mDigitalInAdapter);
            listView.setOnItemSelectedListener(mOnItemSelectedListener);
        }
        listView = (ListView) findViewById(R.id.ls_pound);
        if (listView != null) {
            listView.setAdapter(mPoundAdapter);
        }

        // Initialize the BluetoothChatService to perform bluetooth connections
        mChatService = new BluetoothChatService(mHandler);
    }

    /**
     * Start synchronize digital to Graph
     */

    private void startGraph() {
        mCurrentLineGraph.setTitle("Last " + mGraphView.getSeries().size());
    }

    /**
     * Setup GraphView on screen
     */
    private void GraphSetup() {
        if (mGraphView == null) {
            mGraphView = new GraphView(this);
            LinearLayout.LayoutParams lp = new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,
                    LinearLayout.LayoutParams.MATCH_PARENT);
            mGraphView.setLayoutParams(lp);
            mGraphView.setTitle("Pressure vs Time");
            mGraphView.getGridLabelRenderer().setVerticalAxisTitle("Pressure");

            mGraphView.getGridLabelRenderer().setHorizontalAxisTitle("Time");

            //mGraphView.getViewport().setScalable(true);
            mGraphView.getViewport().setScrollable(true);
        }

        if (mCurrentLineGraph != null) {
            mCurrentLineGraph.setTitle("Last " + mGraphView.getSeries().size());
            mCurrentLineGraph = null;
        }
        mCurrentLineGraph = new LineGraphSeries<>();
        mCurrentLineGraph.setBackgroundColor(Color.RED);
        mCurrentLineGraph.setTitle("From sensor");
        mGraphView.addSeries(mCurrentLineGraph);
        chartContainer.addView(mGraphView);
    }

    /**
     * Clear all Lines from GraphView
     */
    private void GraphClear() {
        if (mGraphView != null) {
            mGraphView.removeAllSeries();
            Log.i(TAG, "Cleared all lines on Graph.");
            if (mCurrentLineGraph != null) {
                mCurrentLineGraph = null;
            }
            mCurrentLineGraph = new LineGraphSeries<>();
            mCurrentLineGraph.setBackgroundColor(Color.RED);
            mCurrentLineGraph.setTitle("From sensor");
            mGraphView.addSeries(mCurrentLineGraph);

            //And startGraph again
            startGraph();
        }
    }

    /**
     * Turn sound bOn
     *
     * @param bOn - true if want to turn alert on, otherwise sound will be turn off.
     */
    private void turnSound(boolean bOn) {
        if (bOn) {
            if (mMPlayerReady) {
                //play and repeat the alert
                if (mMPlayer.isPlaying()) {
                    Log.i(TAG, "turnSound - alert is playing");
                    try {
                        mMPlayer.pause(); // Playback can be paused via pause()
                        mMPlayer.seekTo(0);  //The playback position can be adjusted with a call to seekTo(int).
                    } catch (IllegalStateException e) {
                        Log.w(TAG, "turnSound - IllegalStateException: " + e.getMessage());
                    }
                }
                Log.i(TAG, "turnSound - alert on");
                mMPlayer.start();
            } else {
                Log.i(TAG, "turnSound - sound is not ready to play");
                Toast.makeText(this, "turnSound - sound is not ready to play", Toast.LENGTH_LONG).show();
            }
        } else {
            mMPlayer.pause();

            mMPlayer.seekTo(0);
            Log.i(TAG, "turnSound - alert off");
        }
    }

    /**
     * Digital to Pound conversion.
     * By equation:
     * pound    = 0.224808943871  x force
     * = 0.224808943871  x ( ( digit + 169 ) / 2.29 )
     *
     * @param pressure - digital integer, it should greater than 0, otherwiser 0 will be returned.
     * @return result pound value in float.
     */

    private float digitalToPoundConvert(int pressure) {

        //if (pound < 0) {
        //   return (0);
        //}
        return ((float) pressure);
    }

}
//y=b0+b1x
// (Digital/1024)*5v = to get analog voltage again.

**Comment by jjoe64** [comment]
duplicate
