### ISSUE TITLE
Issue with initializing the graph view

### ISSUE THREAD

**Issue by sayobaid** [jjoe64/GraphView#381]
Sir,
 I imported the .jar file into my project but it shows "import com.jjoe64.graphview.R;" error.
The R.java file is not present in the .jar file.

Help me out..
I am new to android development.

**Comment by sayobaid** [comment]
![2015-12-24 2](https://cloud.githubusercontent.com/assets/16424588/11993139/e590c9da-aa53-11e5-88a0-1cee435e72cd.png)

**Comment by jjoe64** [comment]
if you're using the .jar file you can not use the XML integration. I'm not sure what are you doing in the GraphvIewXML.java file... maybe you should take a look at the doc:
http://www.android-graphview.org/download--getting-started.html
http://www.android-graphview.org/documentation/how-to-create-a-simple-graph
