### ISSUE TITLE
Knowing data point and series index in setOnDataPointTapListener

### ISSUE THREAD

**Issue by nogalavi** [jjoe64/GraphView#382]
First, GraphView is simply great, thank you!!!

I wanted to ask whether there's a way to know what is the index of the selected data point in the series. 
Also, is there a way to know what is the index of the selected series?

Thanks!

**Comment by jjoe64** [comment]
you get the reference to the series and the data point. one way is to iterate through your array and find it via "==". Maybe there is a more elegant solution. But this is a java/android question - not directly related to GraphView. Good luck

**Comment by nogalavi** [comment]
Thanks, what I wanted really is not the reference, but the number of the series. I did some workaround and now it works. Thanks for the reply!
