### ISSUE TITLE
Adding cursors to a line graph

### ISSUE THREAD

**Issue by android002016** [jjoe64/GraphView#383]
I have created a single series line graph using the GraphView where x-axis represents 24 hrs in 1 hour intervals. How can I add 2 cursors on the graph along y-axis that can be moved along  x axis by touch/move. By positioning these cursors on the screen I want to know the interval between any two points on the graph.
Thank you

**Comment by jjoe64** [comment]
hi. this is a very specific case and is not an issue related to graphview. maybe your question is better placed on stackoverflow. Good luck and sorry that I can not help you here
