### ISSUE TITLE
onResume vs. onCreateView: resetting real time graph data

### ISSUE THREAD

**Issue by sho-87** [jjoe64/GraphView#389]
@jjoe64 I have set up graphview to plot real time sensor data in a fragment, the relevant parts of the code are:

```
public void onResume() {
        super.onResume();
        sensorManager.registerListener(this, accelerometer, SensorManager.SENSOR_DELAY_FASTEST);

        //Create graph
        GraphView accGraph = (GraphView) getView().findViewById(R.id.accGraph);

        accXSeries = new LineGraphSeries<DataPoint>();
        accYSeries = new LineGraphSeries<DataPoint>();
        accZSeries = new LineGraphSeries<DataPoint>();

        GraphHelper.initializeGraph(accGraph, accXSeries, accYSeries, accZSeries, MAX_POINTS_DISPLAYED, -10, 10); //just a helper class I wrote. Contains all the code for setting titles, colors etc.
    }
```

and for adding sensor data every 100ms (POLL_FREQUENCY)

```
@Override
    public void onSensorChanged(SensorEvent event) {
        sensor = event.sensor;

        curAcc = event.values;

        long curTime = System.currentTimeMillis();
        long diffTime = (curTime - lastUpdate);

        // only allow one update every POLL_FREQUENCY.
        if (diffTime > POLL_FREQUENCY) {
            lastUpdate = curTime;

            graphXTime += 1d;
            accXSeries.appendData(new DataPoint(graphXTime, curAcc[0]), true, MAX_POINTS_DISPLAYED);
            accYSeries.appendData(new DataPoint(graphXTime, curAcc[1]), true, MAX_POINTS_DISPLAYED);
            accZSeries.appendData(new DataPoint(graphXTime, curAcc[2]), true, MAX_POINTS_DISPLAYED);
        }
    }
```

The one problem I have is that whenever I press back to get back to the graph, the legend items are added again (so I end up with 2 sets of XYZ). I think this is because I added the helper class call in `onResume`

My question is, if I want all of my graph data to be reset every time someone visits the graph (i.e. no data will be persistent), should I be putting my code in `onResume` or `onCreateView`? How should the different elements of the graphview code be distributed in my java class?
I also need to make sure that when someone is not currently looking at the graph, that graphview is not taking up unnecessary amounts of memory by storing past data

**Comment by jjoe64** [comment]
if you are correctly removing the previous series then it should work
