### ISSUE TITLE
Change colors on individual line segments?

### ISSUE THREAD

**Issue by brucetrask** [jjoe64/GraphView#394]
Hello,
Is it possible to set the line color on the individual segments on the line graph?  On one series, I would like the line segments between points that go up to be one color and the ones that go down to be another color. 
Regards,
Bruce

**Comment by prafullsingh** [comment]
Yes it possible you have to customize library files for same.

**Comment by brucetrask** [comment]
Hello,  Thank you for your reply.  I am somewhat new to GraphView.  Could you point me to any  more information on how to do what you are saying?
Thanks in advance.
Bruce

**Comment by jjoe64** [comment]
yes setCustomPaint is the correct point thanks

**Comment by alpebubekir** [comment]
> Hello, Is it possible to set the line color on the individual segments on the line graph? On one series, I would like the line segments between points that go up to be one color and the ones that go down to be another color. Regards, Bruce

I want to do the same but I couldn't find the way actually. İf I am not wrong I need to work with Paint but I don't know what to do. İf you help me I would be very pleased.
