### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'double com.jjoe64.graphview.series.DataPointInterface.getX()' on a null object reference

### ISSUE THREAD

**Issue by Mateusz1992** [jjoe64/GraphView#396]
As in the topic, do you know what can be the reason of the NullPointerException ?

Sample of code:

`if (ileRazyX < ((int) (MAX_X / STEP) + 1)) {

                                                            valuesX[ileRazyX] = new DataPoint(graph2LastXValueX, mrs.get(i).getX() * 9.81);
                                                            SeriesXAccel.appendData(valuesX[ileRazyX], AutoScrollX, ((int) (MAX_X / STEP) + 1));

                                                            if (graph2LastXValueX >= Xview && Lock == true) {
                                                                SeriesXAccel.resetData(new DataPoint[]{});
                                                                graph2LastXValueX = 0;
                                                            } else graph2LastXValueX += STEP;

                                                            if (Lock == true) {
                                                                graphView.getViewport().setMinX(0);
                                                                graphView.getViewport().setMaxX(Xview);
                                                            } /*else {
                                                                graphView.getViewport().setMinX(graph2LastXValueX - Xview);
                                                                graphView.getViewport().setMaxX(Xview);
                                                            }*/

                                                            ileRazyX++;

                                                        } else {
                                                            ileRazyX = 0;

                                                                    /*GraphView.removeView(graphView);
                                                                    GraphView.addView(graphView);*/
                                                        }`

Every help is highly appreciated. Thanks in advance.

**Comment by jjoe64** [comment]
i think it's already fixed or an issue on your implementation side
