### ISSUE TITLE
How to set stepsize using graphview 3.0

### ISSUE THREAD

**Issue by rabiyawaseem94** [jjoe64/GraphView#400]
Hey,
I have used GraphView 3.0 for my ECG analysis project on android. I cant find any option to customize grids ratio or to set step size of my choice on x and y axis. Please let me know If I need to edit the source code or how am I supposed to edit it and which function can be edited for this purpose.
I would be really thankful if you reply ASAP.
Thank you.

**Comment by jjoe64** [comment]
please upgrade to graphview 4 and see documentation

**Comment by rabiyawaseem94** [comment]
Thank you so much sir.

Sent from Yahoo Mail on Android 
 
  On Mon, Jun 20, 2016 at 15:20, Jonas Gehring<notifications@github.com> wrote:   
please upgrade to graphview 4 and see documentation

**Comment by rabiyawaseem94** [comment]
Helo sir,Can you please further elaborate about the scaling. I cannot find any function for this. If you know please mention the function of graphview 4.0.It would be really grateful.Thank you.

Sent from Yahoo Mail on Android 
 
  On Mon, Jun 20, 2016 at 19:55, Rabiya Waseem<rabiya.waseem@ymail.com> wrote:   Thank you so much sir.

Sent from Yahoo Mail on Android 
 
  On Mon, Jun 20, 2016 at 15:20, Jonas Gehring<notifications@github.com> wrote:   
please upgrade to graphview 4 and see documentation
