### ISSUE TITLE
Bargraph: changing the thickness of the bars on 4.0.1

### ISSUE THREAD

**Issue by kachenkore** [jjoe64/GraphView#401]
Hello, i'm plotting some real-time data on a bargraph and in the upgrade from 4.0.0 to 4.0.1 they lost the 'thickness' i set with setSpacing(). On 4.0.0 the bars get plotted as i want (see picture) and on 4.0.1 they are just a pixel wide... what could be the issue?

Thank you in advance.
![screenshot_2016-01-13-20-47-54](https://cloud.githubusercontent.com/assets/19777941/15822243/e3fe7e14-2bf4-11e6-9e53-cbcfaeb21c2d.png)

**Comment by jjoe64** [comment]
it's working for me in currenct branch. maybe some problems with your implementation. please send me a complete example where i can reproduce it.
