### ISSUE TITLE
Can we define major and minor grid?

### ISSUE THREAD

**Issue by Gautam87** [jjoe64/GraphView#404]
I want to make an ecg graph in my android app with graph view which requires major and minor grid lines. Is it possible?
![f3e23e1e-1868-11e6-9084-3b397b61dd13](https://cloud.githubusercontent.com/assets/19686155/16294773/4dd50ee0-3940-11e6-8041-b7a5875a0223.jpg)

**Comment by jjoe64** [comment]
Not possible out of the box. But should not be hard to modify the code for
this. See the class gridlabel renderer

---
von unterwegs gesendet
Am 23.06.2016 09:15 schrieb "Gautam87" <notifications@github.com>:
