### ISSUE TITLE
Second Y-Scale and real time updates

### ISSUE THREAD

**Issue by lukeskymuh** [jjoe64/GraphView#405]
I am ploting (x, y plot) sensor data every few seconds using time (format hh:mm) on the x axis. and i have 2 issues:

1)I tried to update the data from the second y scale using the update method. Unfortunately it didn't work. Is this possible? 

2)My plot only appears when there are approximately 5 or more data points available. Do you have an idea what is reason?

**Comment by jjoe64** [comment]
point 2 please make a separate issue with example code to reproduce
