### ISSUE TITLE
Grid Label Renderer Not Working

### ISSUE THREAD

**Issue by bmdalton** [jjoe64/GraphView#407]
In your grid label rendering documentation, it says setTextSize(float textSize) will change the size of the axis titles (but can be override by the specific commands for the horizontal and vertical axis.  However, when I use setTextSize(float) OR I try to use the setVerticalAxisTitleTextSize(float) and setHorizontalAxisTitleTextSize(float), there is absolutely no change in text size.

I have tried changing the location of the setTextSize and have attached some of my code below.

<img width="789" alt="screen shot 2016-06-28 at 9 17 35 am" src="https://cloud.githubusercontent.com/assets/19672758/16416637/3339f4f4-3d11-11e6-9a21-72b477df1c3b.png">

**Comment by bmdalton** [comment]
This is not a solution, but I think setting the viewport manually affects the ability of Grid Label Renderer.  In a separate attempt to highlight the zero lines, I used
`graph.getViewport().setHighlightZeroLines(true);`
and the lines would not show up.  After commenting out the section where I manually set the X and Y bounds of the viewport, the zero lines showed up with no problem.

If this is indeed the issue, it is far more concerning that enabling one feature disables others.

**Comment by jjoe64** [comment]
Hi,
I checked it and found no issue there.
`graph.setTitleTextSize(80);` will only change the title of the graph. I could not found a wrong hint in the documentation.
`graph.getGridLabelRenderer().setVerticalAxisTitleTextSize(80);` and/or horizontal worked as expected for me.

Example code:

```
GraphView graph = (GraphView) rootView.findViewById(R.id.graph);
        LineGraphSeries<DataPoint> series = new LineGraphSeries<DataPoint>(new DataPoint[] {
                new DataPoint(0, 1),
                new DataPoint(1, 5),
                new DataPoint(2, 3),
                new DataPoint(3, 2),
                new DataPoint(4, 6)
        });
        graph.addSeries(series);

        // titles
        graph.setTitle("Chart Title");
        graph.getGridLabelRenderer().setVerticalAxisTitle("Vertical Axis");
        graph.getGridLabelRenderer().setHorizontalAxisTitle("Horizontal Axis");

        // optional styles
        //graph.setTitleTextSize(80);
        //graph.setTitleColor(Color.BLUE);
        graph.getGridLabelRenderer().setVerticalAxisTitleTextSize(80);
        graph.getGridLabelRenderer().setVerticalAxisTitleColor(Color.BLUE);
        graph.getGridLabelRenderer().setHorizontalAxisTitleTextSize(80);
        graph.getGridLabelRenderer().setHorizontalAxisTitleColor(Color.BLUE);
```

I also could not find a bug with the draw zero stuff. If you have still problems here, please create a new issue with the example code that I can copy&paste and reproduce it. Thanks
