### ISSUE TITLE
Realtime Graph Resets when phone is rotated

### ISSUE THREAD

**Issue by bmdalton** [jjoe64/GraphView#408]
How do I get the same graph to continue graphing when the phone is rotated, rather then restarting at zero.

I have data coming in to the graph from a USB Serial Port and is being appended to my series in real time.  When in either orientation, the graph properly graphs the data, but when I try to switch between portrait and landscape screens on the phone (I rotate it), the graph restarts graphing the data from zer0.

**Comment by jjoe64** [comment]
after rotating the views are re-created. so you have to care about the data. more information in android documentation.
https://developer.android.com/reference/android/app/Activity.html
search for savedInstanceState

**Comment by bmdalton** [comment]
Thank you -- for other people who may have the same issue, instead of searching through the documentation, add " android:configChanges="orientation|screenSize" " at the end of the opening brackets of the activity you want to be able to have rotate on the screen inside the Android Manifest like below:
<img width="397" alt="screen shot 2016-06-30 at 9 27 46 am" src="https://cloud.githubusercontent.com/assets/19672758/16489763/f4004226-3ea4-11e6-85db-f758e55e864e.png">
