### ISSUE TITLE
Weird artifact in top left corner of graph.

### ISSUE THREAD

**Issue by vbhide** [jjoe64/GraphView#410]
I’ve been working on an Android App that utilizes the GraphView tool (4.0.1) for plotting data. I must say that it’s been a great experience so far. It was easy to grasp and integrate into our code. 

There is however 1 observation that we seem to be having, and we’re not sure of what is causing it. Please see the 2 screen shots below, and notice the “artifact” (highlighted yellow) that appears in the top left corner of the graph. 

Plotting logic - Ymax and Ymin are set as 390 and 40, respectively. So user only sees values plotted within this range. Values between 390 and 400 are plotted as 390 (intentionally by design). Any values above 400 and below 40 are still plotted, but not visible to the user due to the Ymax and Ymin setting. An external device sends a value every minute to the phone (Android App), and this value is plotted.

Any thoughts on what may be causing this? I can assure you that the X and Y values being sent to the utility are correct. 

Any input from you is greatly appreciated.

Thank you.
![capture_1](https://cloud.githubusercontent.com/assets/20213265/16467621/24a77604-3e16-11e6-8e85-6b3cf6b4a0a5.JPG)
![capture_2](https://cloud.githubusercontent.com/assets/20213265/16467622/24a8360c-3e16-11e6-8d47-107df46d9781.JPG)

**Comment by chrisfrice** [comment]
I've seen something like this too (intermittent crap at the upper left) in one of my test projects, input data was good.  Never figured it out.

**Comment by jjoe64** [comment]
if s/o can send me an example code where i can test, would be great

**Comment by jjoe64** [comment]
should be fixed in the meanwhile with v4.2.1
