### ISSUE TITLE
setScrollable and setScalable for Y and X-axis

### ISSUE THREAD

**Issue by Albiwalbi** [jjoe64/GraphView#419]
Is it possible to make the viewport scalable and scrollable via the Y-axis AND the X-axis see you can get a free viewport to move?

Thanks in advance! 😄

**Comment by jjoe64** [comment]
hi this is currently in development. there will be a new release with this feature in august

**Comment by Albiwalbi** [comment]
Thank you for the quick response, can't wait for it!
