### ISSUE TITLE
Get Value of Realtime Data on Y-Axis

### ISSUE THREAD

**Issue by bmdalton** [jjoe64/GraphView#424]
If we have a realtime graph, is there a way to mark the value of where the graph is on the y-axis (say the line is relatively constant).  I know we can set the number of tick marks, as well as manually set the viewport, but if we do not know what the value of the line will be, is there a way we can display it's value on the graph's axis?

**Comment by jjoe64** [comment]
Hi I dont exactly understand what you want. maybe show me a picture?

**Comment by jjoe64** [comment]
close because of no response
