### ISSUE TITLE
look for a way to handle NaN or infinite results in graphs

### ISSUE THREAD

**Issue by HansJoergSchmidt** [jjoe64/GraphView#435]
Hi,

I'm trying to use your libary to plot function Graphs using the line graph object.
This works quite well, but Fails in case of singularities ... f(x) = 1/x. So far I work around this by analying and calculating pole Points to split the graph into separate series. See example...
But by allowing for a parametric plot the effort for this is very high and would make my routines very slow.

In Microsofts MS Chart component I can handle this by Setting "empty" Points within a series. This stops line Graphs from plotting and let's it follow up with the next valid data Point.

I was desperatly looking for similar, but haven't found it in graphview.
Is there a simple way to accomplish this?

![example](https://cloud.githubusercontent.com/assets/21422453/18157592/c17a921a-701e-11e6-995e-9943c28d2d6a.PNG)

Kind regards,
your Fan Hans Joerg.

**Comment by jjoe64** [comment]
you can do this as soon as i implement incomplete data via NaN or null values see #442
