### ISSUE TITLE
Graphview not showing if in scroll view

### ISSUE THREAD

**Issue by leiboldm** [jjoe64/GraphView#437]
Note: this is a duplicate of https://github.com/jjoe64/GraphView/issues/17, but github won't let me reopen that bug so I'm duplicating it instead.  This bug still exists and graphview doesn't even bother to throw an exception when it occurs.

Sample code:

super.onCreate(b);

     setContentView(R.layout.graph);
     LinearLayout graphbox = (LinearLayout)findViewById(R.id.graphbox);

    GraphViewSeries exampleSeries = new GraphViewSeries(new GraphViewData[] {
              new GraphViewData(1, 2.0d)
              , new GraphViewData(2, 1.5d)
              , new GraphViewData(3, 2.5d)
              , new GraphViewData(4, 1.0d)
    });

    GraphView graphView = new LineGraphView(
          this // context
          , "GraphViewDemo" // heading
    );
    graphView.addSeries(exampleSeries); // data

    graphbox.addView(graphView);
}

and

<?xml version="1.0" encoding="utf-8"?>

android:layout_width="fill_parent"
android:layout_height="fill_parent" >

<LinearLayout 
    android:orientation="vertical"
    android:id="@+id/graphbox"
     android:minHeight="500dip"
    android:layout_width="fill_parent"
    android:layout_height="wrap_content" >
</LinearLayout>
inside a theme dialog type activity shows nothing. I used your example from your site to make sure it wasn't my stuff. I have previously had success with this.

**Comment by jjoe64** [comment]
this is related to very old graphview version. please update to 4.2 and try again

**Comment by oussd** [comment]
I'm still having this same problem with the latest version. How can you change the graphview hight from the program ?
