### ISSUE TITLE
Different plotting whit 4.2 vs 4.1

### ISSUE THREAD

**Issue by Ubmeje** [jjoe64/GraphView#448]
Maybe this is an issues whit 4.2
"The Spikes" appears when zooming in whit 4.2 
Whit 4.1 they are always plotted.
I am beginner so maybe i doing something wrong.
Here is the code:

        GraphView graph = (GraphView) findViewById(R.id.graph_test);
        LineGraphSeries<DataPoint> series = new LineGraphSeries<DataPoint>(new DataPoint[] {
                new DataPoint(0, 1),
                new DataPoint(1, 1),
                new DataPoint(1, 2),
                new DataPoint(2, 2),
                new DataPoint(2, 1),
                new DataPoint(3, 1),
                new DataPoint(3.01, 2),
                new DataPoint(4, 2),
                new DataPoint(4.01, 1),
                new DataPoint(5, 1),
                new DataPoint(5.001, 2),
                new DataPoint(6, 2),
                new DataPoint(6.001, 1),
                new DataPoint(7, 1),
                new DataPoint(7.009, 2),
                new DataPoint(8, 2),
                new DataPoint(8.009, 1),
                new DataPoint(9, 1),
                //spikes
                new DataPoint(9, 1),
                new DataPoint(9.001, 2),
                new DataPoint(9.002, 1),
                new DataPoint(10, 1),
                new DataPoint(10.002, 2),
                new DataPoint(10.004, 1),
                new DataPoint(11, 1),
                new DataPoint(11.004, 2),
                new DataPoint(11.008, 1),
                new DataPoint(12, 1),
                new DataPoint(12.005, 2),
                new DataPoint(12.010, 1),
                new DataPoint(13, 1),
                new DataPoint(13, 2),
                new DataPoint(13, 1),
                new DataPoint(14, 1),
                new DataPoint(14.01, 2),
                new DataPoint(14.02, 1),
                new DataPoint(30, 1),
        });
        graph.getViewport().setXAxisBoundsManual(true);
        graph.getViewport().setMinX(0);
        graph.getViewport().setMaxX(30);

        graph.getViewport().setScrollable(true);
        graph.getViewport().setScalable(true);

        graph.addSeries(series);

**Comment by Ubmeje** [comment]
Here is Pictures:

Version 4.1
![screenshot_2016-11-24-07-01-46](https://cloud.githubusercontent.com/assets/23706008/20588531/2aa97eb6-b216-11e6-93dd-7d3d97c95b2b.png)


Version 4.2
![screenshot_2016-11-24-07-05-41](https://cloud.githubusercontent.com/assets/23706008/20588449/88064be4-b215-11e6-9d81-e9880f6e77ee.png)

**Comment by jjoe64** [comment]
yes there is currently a bug. I already have a patch but I need to do some checks. I will release a new version in the next few days. Thanks for the report

**Comment by jjoe64** [comment]
ok i just checked your example and it is working correctly in current version - which is not released yet. will be released in the next few days
