### ISSUE TITLE
Using a for() function to make DataPoints

### ISSUE THREAD

**Issue by dovshmuel** [jjoe64/GraphView#457]
Here is my code:

 GraphView graph = (GraphView) findViewById(R.id.graph);
        LineGraphSeries<DataPoint> series = new LineGraphSeries<>(new DataPoint[]{

                for(int i = 0; i < 10; i++){
            new DataPoint(i, Double.parseDouble(data[i][1]));
        }
        });
        graph.addSeries(series);

Why can't I put the for() loop inside of this? How else could I write this so that I have a for() loop that makes new DataPoints?

**Comment by minorsecond** [comment]
@dovshmuel did you figure this out? I'm trying to do something very similar.
