### ISSUE TITLE
I cant Re-Write the graph in a Graphview I'm getting some extra line?

### ISSUE THREAD

**Issue by Ragulmurugan** [jjoe64/GraphView#572]
I'm trying to plot the value in GraphView and for 2nd time i'm trying plot the another set of data in the same graphview but I'm getting some extra unwanted line in the graphview.
![device-2018-04-23-172518](https://user-images.githubusercontent.com/36410172/39127399-88fb5f28-4722-11e8-8265-0517d88b9cc3.png)

in the above picture Red colored marked line is the extra line I'm getting while plotting the graph.

I'm using com.jjoe64.graphview.GraphView

**Comment by jjoe64** [comment]
pls check your data. if its for sure a graphview bug pls provide a complete isolated example project so i can debug it

**Comment by Ragulmurugan** [comment]
Sure , I'll send you isolated project for you as soon as possible.

**Comment by Ragulmurugan** [comment]
Here I'm adding the link for my code
https://drive.google.com/open?id=1K0oQJIEcs8xW_UDFK6oNoAN8bwr94xoz

![dfc_requirment](https://user-images.githubusercontent.com/36410172/39421528-17fec75a-4c87-11e8-8a07-24404ac6a4f7.png)


while plotting data for first time it prints properly but for the second time it continues from the last position of the previous graph , I want to plot the fresh live graph so previous plotted graph should be removed.
