### ISSUE TITLE
Does Graphview allow setting ticks on x- or y-axis?

### ISSUE THREAD

**Issue by sonicsynergies** [jjoe64/GraphView#573]
I want to make unequal tick marks on y-axis. Graphview generally gives .setNumVerticalLabales(int) and divides the minY and maxY based on the int number given. But I want to mark unequal ticks based on the frequency numbers generated. For example: for a range of 90 to 400 on y-axis, 97.99 is the first tick, 103.83, the second and so on (frequencies for musical notes) for 25 ticks. is that possible? It can be a rounded 98, 104, etc. Not necessary to have double. Pl let me know. Refer to [ https://sonicsynergies.github.io/Gamaka/](url)

**Comment by sonicsynergies** [comment]
No response yet?

**Comment by jjoe64** [comment]
pls take a look at the demo app, there are all features shown
