### ISSUE TITLE
Refactor android.support to androidx

### ISSUE THREAD

**Issue by Rexios80** [jjoe64/GraphView#574]
The Android support libraries are being refactored into androidx. Dependencies such as GraphView will need to refactor their support library dependencies or projects that depend on both them and androidx will not build properly.

**Comment by blizzard4591** [comment]
I have this problem - an app buiding on AndroidX. Is there a workaround? I want to use GraphView, but I do not know enough about android to fix this myself.

**Comment by Rexios80** [comment]
I just gave up on using Androidx for now. It's not worth the headache considering Androidx isn't even in a stable release yet. So the work around is: don't use Androidx right now.
