### ISSUE TITLE
Error sync Gradle

### ISSUE THREAD

**Issue by syedafeef** [jjoe64/GraphView#634]
I'm getting this error when i add GrapgView dependency

Android resource linking failed
D:\ArduinoUSB\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1917: error: resource android:attr/fontStyle not found.
D:\ArduinoUSB\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1917: error: resource android:attr/font not found.
D:\ArduinoUSB\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1917: error: resource android:attr/fontWeight not found.
error: failed linking references.

and my app Gradle is:

apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion '28.0.3'

    defaultConfig {
        applicationId "com.hariharan.arduinousb"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:25.4.0'
    implementation files('libs/usbserial.jar')
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.jjoe64:graphview:4.2.2'

}

**Comment by WyFryMU** [comment]
`implementation 'com.jjoe64:graphview:4.2.2'`
You're using version 4.2.2, which doesn't exist. 4.2.1 is the newest.

**Comment by NekomiFisher** [comment]
You may want to check the "Download and getting started" page as it may currently have a typo. I experienced a similar issue with the link being displayed as being "implementation 'com.jjoe64:graphview:4.2.2'" instead of 4.2.1. Just have to add, awesome work though.
