### ISSUE TITLE
onClickListner 

### ISSUE THREAD

**Issue by syedafeef** [jjoe64/GraphView#636]
The on click listener is working fine but the area for the click is too large. so it's clicking on multiple data points. Is there any way to restrict the click area?

Any help will be appreciated.
Thank you

**Comment by lslemon** [comment]
Hi syedafeef!!
I had a similar issue before, what I did was I created a new Series and one of the method I overwrote was the **findDataPoint** method used by **onTap**. Within this method it says the tapped point will only work when the finger event is at most 120px away. You can reduce this size to suit your needs

**Comment by syedafeef** [comment]
> Hi syedafeef!!
> I had a similar issue before, what I did was I created a new Series and one of the method I overwrote was the **findDataPoint** method used by **onTap**. Within this method it says the tapped point will only work when the finger event is at most 120px away. You can reduce this size to suit your needs

**Comment by syedafeef** [comment]
Thank you but I did a workaround for this.
